export const WA_NUMBER = "51900025403";
export const WA_BASE   = `https://wa.me/${WA_NUMBER}`;
export const wm = (text = "") =>
  text ? `${WA_BASE}?text=${encodeURIComponent(text)}` : WA_BASE;

export const COMPANY = {
  name:      "Recursos Tecnológicos S.A.C.",
  phone:     "+51 900 025 403",
  email:     "recursostecnologicossac@gmail.com",
  address:   "Av. Alameda Sur 547, Chorrillos, Lima",
  address2:  "Jr. Leticia 939, Lima",
  facebook:  "https://facebook.com/rectecnologicosperu",
  instagram: "https://instagram.com/recursostecnologicos",
  hours:     "Lun–Sáb · 9am – 6pm",
};

export const TABS = [
  { id: "inicio",    label: "Inicio"    },
  { id: "productos", label: "Productos", hasMega: true },
  { id: "asesoria",  label: "Asesoría"  },
  { id: "nosotros",  label: "Nosotros"  },
  { id: "contacto",  label: "Contacto"  },
];

const Q  = "?auto=format&fit=crop&w=700&q=82";
const QL = "?auto=format&fit=crop&w=1000&q=85";

export const PRODUCTS = [
  {
    id: "lifepo4",
    label: "Baterías LiFePO4",
    icon: "🔒",
    items: [
      {
        id:      "bateria-sellada",
        name:    "Batería Sellada 12V - 24V",
        badge:   "LiFePO4",
        tagline: "12.8 V / 25.6 V · Deep Cycle · BMS integrado",
        img:     "/sealed-1.avif",
        imgL:    "/sealed-1.avif",
        images:  ["/sealed-1.avif", "/sealed-2.avif", "/sealed-3.avif"],
        waMsg:   "Quiero cotizar baterías LiFePO4 selladas 12V / 24V",
        specs: [
          ["Voltajes disponibles",  "12.8 V · 25.6 V"],
          ["Modelos 12V",           "6 Ah · 24 Ah · 50 Ah · 100 Ah · 200 Ah"],
          ["Energía 12V",           "76.8 / 307 / 640 / 1,280 / 2,560 Wh"],
          ["Modelos 24V",           "50 Ah · 100 Ah · 200 Ah"],
          ["Energía 24V",           "1,280 / 2,560 / 5,120 Wh"],
          ["Celda",                 "32700 LiFePO4"],
          ["Voltaje carga 12V",     "14.6 V"],
          ["Voltaje carga 24V",     "29.2 V"],
          ["Ciclos",                "≥ 6,000 (DoD 95%)"],
          ["Temp. descarga",        "-20 °C a 60 °C"],
          ["Temp. carga",           "0 °C a 45 °C"],
          ["Aplicaciones",          "Solar · UPS · Marina · Telecom · Vehículos · Alarmas"],
          ["Certificaciones",       "CE · RoHS · UN38.3"],
          ["Garantía",              "2 años"],
        ],
        desc: "Baterías LiFePO4 selladas disponibles en 12V y 24V para todo tipo de aplicación. La serie 12V va desde 6Ah (moto/UPS) hasta 200Ah para sistemas solares de gran autonomía. La serie 24V ofrece hasta 5,120 Wh en un solo módulo, ideal para inversores industriales, marina y telecomunicaciones. BMS integrado, sin mantenimiento, reemplazo directo de plomo-ácido AGM/GEL.",
      },
      {
        id:      "wall-battery",
        name:    "Batería Empotrada PowerWall LiFePO4",
        badge:   "Wall-Mounted",
        tagline: "24V / 51.2V · 5–30 KWh · Off-grid & Híbrido",
        img:     "/wall-battery-1.avif",
        imgL:    "/wall-battery-2.avif",
        images:  ["/wall-battery-1.avif", "/wall-battery-2.avif", "/wall-battery-3.avif"],
        waMsg:   "Quiero cotizar Batería Empotrada PowerWall LiFePO4",
        specs: [
          ["Tipo de batería",      "LiFePO4"],
          ["Voltajes disponibles", "24V · 51.2V"],
          ["Capacidades 24V",      "100Ah / 200Ah / 300Ah / 400Ah / 600Ah"],
          ["Energía 24V",          "5 / 10 / 15 / 20 / 30 KWh"],
          ["Capacidades 51.2V",    "50Ah / 80Ah / 100Ah / 200Ah"],
          ["Energía 51.2V",        "2.56 / 4.1 / 5.12 / 10.24 KWh"],
          ["Potencia de salida",   "3.8 KW (24V) · 5–10 KW (51.2V)"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Tipo de instalación",  "Wall-Mounted (Empotrado en pared)"],
          ["Protección",           "IP54"],
          ["Display",              "LCD + CAN Option"],
          ["Comunicación",         "CAN · RS485"],
          ["Ciclos de vida",       "≥ 6,000 ciclos"],
          ["Dimensiones",          "530 × 480 × 165 mm"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 empotrada en pared (PowerWall) disponible en 24V y 51.2V con capacidades desde 5KWh hasta 30KWh. Diseñada para instalación residencial y comercial en sistemas solares off-grid e híbridos. Carcasa metálica IP54, display LCD, comunicación CAN/RS485 compatible con los principales inversores del mercado.",
      },
      {
        id:      "bateria-movil",
        name:    "Batería Móvil LiFePO4 48V",
        badge:   "Floor Type",
        tagline: "48V / 51.2V · 5 – 30 KWh · Off-grid & Híbrido · Con ruedas",
        img:     "/movil-2.avif",
        imgL:    "/movil-2.avif",
        images:  ["/movil-2.avif", "/movil-1.avif", "/movil-3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil LiFePO4 48V",
        specs: [
          ["Tipo de batería",      "LiFePO4"],
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 400Ah · 600Ah"],
          ["Energía disponible",   "5 / 10 / 15 / 20 / 30 KWh"],
          ["Potencia de salida",   "10 – 20 KW"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Tipo",                 "Floor Type (con ruedas)"],
          ["Protección",           "IP54"],
          ["Comunicación",         "CAN · RS-232 · RS485"],
          ["Display",              "LCD + CAN Option"],
          ["BMS / Bluetooth",      "Sí"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Aplicación",           "Home Solar Energy System"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 de piso con ruedas, diseñada para movilidad y fácil instalación en hogares y comercios. Disponible en 48V/51.2V con capacidades de 5KWh a 30KWh. Compatible con sistemas solares off-grid e híbridos de 10–20KW. BMS integrado con Bluetooth, display LCD, comunicación CAN/RS485. Ideal como almacenamiento de energía solar con máxima flexibilidad de ubicación.",
      },
      {
        id:      "bateria-movil-mini",
        name:    "Batería Móvil Mini LiFePO4",
        badge:   "Mobile",
        tagline: "48V / 51.2V · 100 / 200 / 300 Ah · Compacta con ruedas",
        img:     "/movil-mini-2.avif",
        imgL:    "/movil-mini-2.avif",
        images:  ["/movil-mini-2.avif", "/movil-mini-1.avif", "/movil-mini-3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil Mini LiFePO4",
        specs: [
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 320Ah"],
          ["Energía nominal",      "4.8 / 5.12 / 9.6 / 10.24 / 14.4 / 15.36 KWh"],
          ["Tipo",                 "Mobile LiFePO4 (con ruedas)"],
          ["BMS",                  "Smart BMS — sobredescar., sobrecarga, cortocircuito, ecualización"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Temp. operación",      "-20 °C a 60 °C (recomendado 10–40 °C)"],
          ["Temp. almacenamiento", "-10 °C a 50 °C"],
          ["Dimensiones",          "700 × 490 × 170 mm"],
          ["Peso",                 "47 kg"],
          ["Display",              "LCD + CAN Option"],
          ["Comunicación",         "RS485 · CAN · WiFi · Bluetooth"],
          ["Aplicaciones",         "Solar · UPS · Marina · Silla eléctrica · Herramientas"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Versión compacta de la batería móvil LiFePO4, con formato horizontal tipo maleta y ruedas para fácil traslado. Disponible en 48V/51.2V con capacidades de 100Ah a 300Ah (4.8–15.36KWh). Smart BMS integrado con protección completa, WiFi y Bluetooth. Compatible con los principales inversores del mercado. Ideal para uso residencial, UPS, marina y movilidad eléctrica.",
      },
    ],
  },
  {
    id: "solar",
    label: "Energía Solar",
    icon: "☀️",
    items: [
      {
        id:      "paneles",
        name:    "Paneles Solares Monocristalinos",
        badge:   "Fotovoltaico",
        tagline: "400 – 550 W · Eficiencia 20–22 %",
        img:     `https://images.unsplash.com/photo-1509391366360-2e959784a276${Q}`,
        imgL:    `https://images.unsplash.com/photo-1509391366360-2e959784a276${QL}`,
        waMsg:   "Quiero cotizar paneles solares monocristalinos",
        specs: [
          ["Potencia pico",     "400 / 450 / 500 / 550 W"],
          ["Eficiencia",        "20 – 22 %"],
          ["Voltaje Voc",       "48 – 52 V"],
          ["Corriente Isc",     "10 – 13 A"],
          ["Temperatura op.",   "-40 °C a 85 °C"],
          ["Marco",             "Aluminio anodizado"],
          ["Garantía",          "25 años de producto"],
        ],
        desc: "Paneles monocristalinos de alta eficiencia para instalaciones residenciales, comerciales e industriales en todo el Perú. Mayor rendimiento en condiciones de alta irradiación solar propia de Lima y la sierra peruana. Incluye garantía de 25 años.",
      },
      {
        id:      "inversores",
        name:    "Inversores Híbridos On/Off-grid",
        badge:   "Inversor",
        tagline: "3 – 10 kW · MPPT integrado · WiFi",
        img:     `https://images.unsplash.com/photo-1545208075-95a3e09c1ea1${Q}`,
        imgL:    `https://images.unsplash.com/photo-1545208075-95a3e09c1ea1${QL}`,
        waMsg:   "Quiero cotizar inversores híbridos solares",
        specs: [
          ["Potencia",          "3 kW / 5 kW / 8 kW / 10 kW"],
          ["Modos",             "On-grid · Off-grid · Híbrido"],
          ["MPPT integrado",    "Eficiencia 98 %"],
          ["Voltaje de batería","48 V (100–600 V string)"],
          ["Monitoreo",         "WiFi + App móvil"],
          ["Protecciones",      "Sobrecarga · CC · temperatura"],
          ["Baterías compat.",  "LiFePO4 · Li-Ion · Plomo-ácido"],
        ],
        desc: "Inversores híbridos con conmutación automática entre red eléctrica, paneles solares y baterías, sin intervención del usuario. Monitoreo en tiempo real desde cualquier dispositivo. Compatible con baterías LiFePO4 y sistemas de hasta 3 fases.",
      },
      {
        id:      "mppt",
        name:    "Controladores MPPT",
        badge:   "MPPT",
        tagline: "20 – 100 A · 12/24/48 V · 98 % efic.",
        img:     `https://images.unsplash.com/photo-1559302504-64aae6ca6b6d${Q}`,
        imgL:    `https://images.unsplash.com/photo-1559302504-64aae6ca6b6d${QL}`,
        waMsg:   "Quiero cotizar controladores MPPT",
        specs: [
          ["Corriente de carga","20 / 40 / 60 / 100 A"],
          ["Voltaje de sistema","12 V / 24 V / 48 V (auto)"],
          ["Eficiencia MPPT",   "≥ 98 %"],
          ["Voltaje PV máx.",   "150 / 200 V"],
          ["Display",           "LCD + Bluetooth"],
          ["Protecciones",      "Sobrecarga · Inversión de pol."],
          ["Baterías compat.",  "LiFePO4 · Li-Ion · AGM · GEL"],
        ],
        desc: "Controladores de carga MPPT de alta eficiencia para maximizar la generación solar en cualquier condición de nubosidad o temperatura. Soportan baterías LiFePO4 con perfil de carga programable vía Bluetooth. Display LCD con historial de datos.",
      },
    ],
  },
  {
    id: "vehiculos",
    label: "Vehículos Eléctricos",
    icon: "⚡",
    items: [
      {
        id:      "scooter",
        name:    "Scooter Eléctrico",
        badge:   "Scooter",
        tagline: "2,000 – 5,000 W · Hasta 120 km",
        img:     `https://images.unsplash.com/photo-1558618666-fcd25c85cd64${Q}`,
        imgL:    `https://images.unsplash.com/photo-1558618666-fcd25c85cd64${QL}`,
        waMsg:   "Quiero información sobre scooter eléctrico",
        specs: [
          ["Motor",          "2,000 – 5,000 W BLDC sin escobillas"],
          ["Batería",        "60 – 72 V / 20 – 40 Ah Li-Ion / LiFePO4"],
          ["Autonomía",      "60 – 120 km por carga"],
          ["Velocidad máx.", "45 – 80 km/h"],
          ["Carga",          "4 – 8 horas (estándar)"],
          ["Frenos",         "Disco hidráulico delantero y trasero"],
          ["Garantía",       "12 meses en batería"],
        ],
        desc: "Scooters eléctricos de uso urbano y semipesado, diseñados para Lima y ciudades peruanas. Motor BLDC de alto torque, batería de litio certificada y cargador incluido. Cero mantenimiento de motor, ahorro del 80 % vs gasolina.",
      },
      {
        id:      "mototaxi",
        name:    "Mototaxi Eléctrica",
        badge:   "Mototaxi",
        tagline: "3,000 – 5,000 W · Uso comercial",
        img:     `https://images.unsplash.com/photo-1568772585407-9361f9bf3a87${Q}`,
        imgL:    `https://images.unsplash.com/photo-1568772585407-9361f9bf3a87${QL}`,
        waMsg:   "Quiero información sobre mototaxi eléctrica",
        specs: [
          ["Motor",          "3,000 – 5,000 W BLDC"],
          ["Batería",        "72 V / 40 – 60 Ah LiFePO4"],
          ["Autonomía",      "80 – 120 km por carga"],
          ["Carga útil",     "Hasta 300 kg (pasajeros + carga)"],
          ["Cabina",         "Fibra de vidrio + aluminio"],
          ["Frenos",         "Disco delantero + tambor trasero"],
          ["Garantía",       "12 meses en batería y motor"],
        ],
        desc: "Mototaxis eléctricas diseñadas para el transporte comercial intensivo. Mayor autonomía, menor costo operativo y cero emisiones. Reducción del 85 % en gastos de combustible. Ideal para el mercado peruano de transporte de pasajeros.",
      },
      {
        id:      "cargador",
        name:    "Cargador Eléctrico para Vehículos",
        badge:   "Cargador",
        tagline: "48 / 60 / 72 V · Carga estándar y rápida",
        img:     `https://images.unsplash.com/photo-1593941707882-a5bba14938c7${Q}`,
        imgL:    `https://images.unsplash.com/photo-1593941707882-a5bba14938c7${QL}`,
        waMsg:   "Quiero cotizar cargadores eléctricos para vehículos",
        specs: [
          ["Voltajes",          "48 V / 60 V / 72 V / 84 V"],
          ["Corriente de salida","5 A / 10 A / 20 A"],
          ["Carga rápida",      "Disponible en modelos 10 A y 20 A"],
          ["Protecciones",      "Sobrecarga · Cortocircuito · Temperatura"],
          ["Conector",          "Universal (XLR, GX16, Anderson)"],
          ["Pantalla",          "LED de estado de carga"],
          ["Compatibilidad",    "Li-Ion · LiFePO4 · Plomo-ácido"],
        ],
        desc: "Cargadores inteligentes con corte automático al 100% para proteger la batería. Compatibles con Li-Ion y LiFePO4. Conectores universales compatibles con los principales modelos del mercado peruano. Incluyen ventilación y protección térmica.",
      },
      {
        id:      "moto",
        name:    "Moto Eléctrica",
        badge:   "Moto",
        tagline: "3,000 – 8,000 W · Urbana y semipesada",
        img:     `https://images.unsplash.com/photo-1571068316344-75bc76f77890${Q}`,
        imgL:    `https://images.unsplash.com/photo-1571068316344-75bc76f77890${QL}`,
        waMsg:   "Quiero información sobre motos eléctricas",
        specs: [
          ["Motor",          "3,000 – 8,000 W BLDC de alto torque"],
          ["Batería",        "72 V / 30 – 50 Ah LiFePO4"],
          ["Autonomía",      "80 – 160 km por carga"],
          ["Velocidad máx.", "80 – 120 km/h"],
          ["Frenos",         "Hidráulicos delantero y trasero"],
          ["Suspensión",     "Telescópica delantera · Monoshock trasero"],
          ["Garantía",       "12 meses en batería y motor"],
        ],
        desc: "Motos eléctricas de alta potencia para uso urbano y semipesado. Batería LiFePO4 de larga vida útil, frenos hidráulicos de alto rendimiento y sistema de recuperación de energía por frenado regenerativo. Cero emisiones, máxima eficiencia.",
      },
      {
        id:      "bici",
        name:    "Bicicleta Eléctrica",
        badge:   "E-Bike",
        tagline: "250 – 750 W · Pedal asistido + acelerador",
        img:     `https://images.unsplash.com/photo-1571333250630-f0230c320b6d${Q}`,
        imgL:    `https://images.unsplash.com/photo-1571333250630-f0230c320b6d${QL}`,
        waMsg:   "Quiero información sobre bicicletas eléctricas",
        specs: [
          ["Motor",        "250 – 750 W mid-drive o buje trasero"],
          ["Batería",      "36 V / 48 V · 10 – 20 Ah Li-Ion"],
          ["Autonomía",    "40 – 100 km por carga"],
          ["Modos",        "Pedal asistido (5 niveles) + acelerador"],
          ["Display",      "LCD con indicador de batería y velocidad"],
          ["Frenos",       "Disco hidráulico delantero y trasero"],
          ["Certificación","CE · Norma EN 15194"],
        ],
        desc: "Bicicletas eléctricas para uso urbano y recreativo en Lima. Motor silencioso, batería extraíble que se carga en cualquier tomacorriente y pantalla LCD integrada. Frenos de disco hidráulicos para mayor seguridad en ciudad.",
      },
    ],
  },
  {
    id: "baterias",
    label: "Celdas de Litio",
    icon: "🔋",
    items: [
      {
        id:      "18650",
        name:    "Celda de Litio 18650",
        badge:   "Li-Ion NCM",
        tagline: "2,550 mAh · 3.6 V · EVE · 1,000 ciclos",
        img:     "/celda-18650-1.avif",
        imgL:    "/celda-18650-1.avif",
        images:  ["/celda-18650-1.avif", "/celda-18650-2.avif"],
        waMsg:   "Quiero cotizar celdas de litio 18650 EVE",
        specs: [
          ["Modelo",               "EVE 18650 26V"],
          ["Capacidad nominal",    "2,550 mAh"],
          ["Voltaje nominal",      "3.6 V"],
          ["Energía por celda",    "9.18 Wh"],
          ["Cátodo",               "NCM (Níquel Cobalto Manganeso)"],
          ["Tipo",                 "Li-Ion líquido recargable"],
          ["Ciclos de vida",       "≥ 1,000 ciclos"],
          ["Temp. operación",      "0 °C a 45 °C"],
          ["Dimensiones",          "Ø 18 mm × 65 mm"],
          ["Peso",                 "45 ± 2 g"],
          ["Aplicaciones",         "E-bikes · Scooters · Vehículos eléctricos · Solar · UPS · Montacargas"],
          ["Certificaciones",      "MSDS · CE · RoHS"],
        ],
        desc: "Celda cilíndrica 18650 de EVE Energy, marca Tier-1 de Guangdong, China. Con 2,550 mAh y química NCM ofrece alta densidad de energía para aplicaciones de movilidad eléctrica, herramientas de potencia y sistemas de almacenamiento solar. 1,000 ciclos de vida garantizados con prueba de capacidad verificable.",
      },
      {
        id:      "21700",
        name:    "EVE 21700 50E — Celda Li-Ion",
        badge:   "Li-Ion",
        tagline: "5,000 mAh · 3.65 V · 290 Wh/kg",
        img:     "https://www.evlithium.com/Upfile/image/20230629/20230629170865896589.webp",
        imgL:    "https://www.evlithium.com/Upfile/image/20230629/20230629171062786278.webp",
        waMsg:   "Quiero cotizar celdas EVE 21700 50E",
        specs: [
          ["Modelo",              "EVE 21700 50E"],
          ["Capacidad nominal",   "5,000 mAh"],
          ["Voltaje nominal",     "3.65 V"],
          ["Voltaje máx. carga",  "4.20 V"],
          ["Corriente carga std.", "2.5 A (0.5C)"],
          ["Corriente descarga",  "9.75 A cont. (1.95C)"],
          ["Energía por celda",   "18.25 Wh"],
          ["Densidad energética", "290 Wh/kg"],
          ["Ciclos garantizados", "≥ 1,000 ciclos (80% cap.)"],
          ["Temperatura descarga","-20 °C a 60 °C"],
          ["Dimensiones",         "Ø 21.1 mm × 70.2 mm"],
          ["Peso",                "~70 g"],
          ["Certificaciones",     "UN38.3 · CE · UL"],
        ],
        desc: "La evolución de la 18650: mayor capacidad, mejor densidad energética y gestión térmica superior. El modelo 50E de EVE Energy ofrece 5,000 mAh con una densidad de 290 Wh/kg, ideal para e-bikes de alto rendimiento, packs de motos eléctricas y sistemas de almacenamiento portátil donde el peso es crítico.",
      },
      {
        id:      "33140",
        name:    "EVE C33 33140 — LiFePO4 Cilíndrica",
        badge:   "LiFePO4",
        tagline: "15,000 mAh · 3.2 V · 50 A continua",
        img:     "https://www.evlithium.com/Upfile/image/20230222/20230222103788448844.webp",
        imgL:    "https://www.evlithium.com/Upfile/image/20230717/20230717090049544954.webp",
        waMsg:   "Quiero cotizar celdas EVE LiFePO4 33140",
        specs: [
          ["Modelo",              "EVE C33 (33140)"],
          ["Capacidad nominal",   "15,000 mAh (15 Ah)"],
          ["Voltaje nominal",     "3.2 V"],
          ["Corriente carga rápida","8 A"],
          ["Corriente descarga cont.","50 A (3.3C)"],
          ["Corriente pico",      "100 A (pulso)"],
          ["Ciclos garantizados", "≥ 3,000 ciclos (80% cap.)"],
          ["Temperatura descarga","-20 °C a 55 °C"],
          ["Dimensiones",         "Ø 33.3 mm × 140.8 mm"],
          ["Peso",                "267 g ± 6 g"],
          ["Química",             "LiFePO4 (fosfato de hierro)"],
          ["Certificaciones",     "UN38.3 · IEC 62619 · CE"],
        ],
        desc: "Celda cilíndrica LiFePO4 de gran formato fabricada por EVE Energy. Con 15 Ah y 50 A de descarga continua, es la opción ideal para motocargas eléctricas, triciclos de carga y sistemas de almacenamiento solar de ciclo profundo. Química LiFePO4 = cero riesgo de ignición espontánea.",
      },
      {
        id:      "prismatica",
        name:    "EVE LF280K / LF304 — LiFePO4 Prismática",
        badge:   "LiFePO4",
        tagline: "280 – 304 Ah · 3,500+ ciclos · Solar",
        img:     "https://www.evlithium.com/upfile/20240105/17044190424108549.jpg",
        imgL:    "https://resource.evemall.com/Public/Uploads/uploadfile2/images/20250303/fangxinglinsuan.jpg",
        waMsg:   "Quiero cotizar celdas LiFePO4 prismáticas EVE",
        specs: [
          ["Modelos disponibles",   "LF105 / LF173 / LF230 / LF280K / LF304"],
          ["Capacidades",           "105 / 173 / 230 / 280 / 304 Ah"],
          ["Voltaje nominal",       "3.2 V por celda"],
          ["Corriente carga std.",  "0.5C (140–152 A según modelo)"],
          ["Corriente descarga",    "1C cont. / 3C pico"],
          ["Ciclos garantizados",   "≥ 3,500 ciclos (80% cap.)"],
          ["Temperatura descarga",  "-20 °C a 55 °C"],
          ["Temperatura carga",     "0 °C a 45 °C"],
          ["Carcasa",               "Aluminio prismático sellado"],
          ["Uso principal",         "Solar · EVs · Telecom · UPS · Industria"],
          ["Certificaciones",       "UN38.3 · IEC 62619 · CE · UL"],
        ],
        desc: "El estándar de oro de EVE Energy para almacenamiento de energía solar y packs de vehículos eléctricos pesados. Las celdas LF280K (280 Ah) y LF304 (304 Ah) son las más populares del mundo para baterías de pared solares. Disponemos de toda la gama desde 105 Ah hasta 304 Ah con BMS compatible.",
      },
    ],
  },
];
