export const WA_NUMBER = "51900025403";
export const WA_BASE   = `https://wa.me/${WA_NUMBER}`;
export const wm = (text = "") =>
  text ? `${WA_BASE}?text=${encodeURIComponent(text)}` : WA_BASE;

export const COMPANY = {
  name:      "Recursos Tecnológicos S.A.C.",
  phone:     "+51 900 025 403",
  email:     "recursostecnologicossac@gmail.com",
  address:   "Av. Alameda Sur 547, Chorrillos, Lima",
  address2:  "Jr. Leticia 939, Lima",
  facebook:  "https://facebook.com/rectecnologicosperu",
  instagram: "https://instagram.com/recursostecnologicos",
  hours:     "Lun–Sáb · 9am – 6pm",
};

export const TABS = [
  { id: "inicio",    label: "Inicio"    },
  { id: "productos", label: "Productos", hasMega: true },
  { id: "servicios", label: "Servicios", hasMega: true },
  { id: "asesoria",  label: "Asesoría"  },
  { id: "nosotros",  label: "Nosotros"  },
  { id: "contacto",  label: "Contacto"  },
];

const Q  = "?auto=format&fit=crop&w=700&q=82";
const QL = "?auto=format&fit=crop&w=1000&q=85";

export const PRODUCTS = [
  {
    id: "lifepo4",
    label: "Baterías LiFePO4",
    icon: "🔒",
    items: [
      {
        id:      "bateria-sellada",
        name:    "Batería Sellada 12V - 24V",
        badge:   "LiFePO4",
        tagline: "12.8 V / 25.6 V · Deep Cycle · BMS integrado",
        img:     "/productos/lifepo4/bateria-sellada/1.avif",
        imgL:    "/productos/lifepo4/bateria-sellada/1.avif",
        images:  ["/productos/lifepo4/bateria-sellada/1.avif", "/productos/lifepo4/bateria-sellada/2.avif", "/productos/lifepo4/bateria-sellada/3.avif"],
        waMsg:   "Quiero cotizar baterías LiFePO4 selladas 12V / 24V",
        specs: [
          ["Serie 12V", "__section__"],
          ["Voltajes disponibles",  "12.8 V · 25.6 V"],
          ["Modelos 12V",           "6 Ah · 24 Ah · 50 Ah · 100 Ah · 200 Ah"],
          ["Energía 12V",           "76.8 / 307 / 640 / 1,280 / 2,560 Wh"],
          ["Voltaje de carga",      "14.6 V"],
          ["Serie 24V", "__section__"],
          ["Modelos 24V",           "50 Ah · 100 Ah · 200 Ah"],
          ["Energía 24V",           "1,280 / 2,560 / 5,120 Wh"],
          ["Voltaje de carga",      "29.2 V"],
          ["Celda & Rendimiento", "__section__"],
          ["Celda",                 "32700 LiFePO4"],
          ["Ciclos",                "≥ 6,000 (DoD 95%)"],
          ["Temp. descarga",        "-20 °C a 60 °C"],
          ["Temp. carga",           "0 °C a 45 °C"],
          ["General", "__section__"],
          ["Aplicaciones",          "Solar · UPS · Marina · Telecom · Vehículos · Alarmas"],
          ["Certificaciones",       "CE · RoHS · UN38.3"],
          ["Garantía",              "2 años"],
        ],
        desc: "Baterías LiFePO4 selladas disponibles en 12V y 24V para todo tipo de aplicación. La serie 12V va desde 6Ah (moto/UPS) hasta 200Ah para sistemas solares de gran autonomía. La serie 24V ofrece hasta 5,120 Wh en un solo módulo, ideal para inversores industriales, marina y telecomunicaciones. BMS integrado, sin mantenimiento, reemplazo directo de plomo-ácido AGM/GEL.",
      },
      {
        id:      "wall-battery",
        name:    "Batería Empotrada PowerWall LiFePO4",
        badge:   "Wall-Mounted",
        tagline: "24V / 51.2V · 5–30 KWh · Off-grid & Híbrido",
        img:     "/productos/lifepo4/wall-battery/1.avif",
        imgL:    "/productos/lifepo4/wall-battery/2.avif",
        images:  ["/productos/lifepo4/wall-battery/1.avif", "/productos/lifepo4/wall-battery/2.avif", "/productos/lifepo4/wall-battery/3.avif"],
        waMsg:   "Quiero cotizar Batería Empotrada PowerWall LiFePO4",
        specs: [
          ["Serie 24V", "__section__"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 400Ah · 600Ah"],
          ["Energía disponible",   "5 / 10 / 15 / 20 / 30 KWh"],
          ["Potencia de salida",   "3.8 KW"],
          ["Serie 51.2V", "__section__"],
          ["Capacidades",          "50Ah · 80Ah · 100Ah · 200Ah"],
          ["Energía disponible",   "2.56 / 4.1 / 5.12 / 10.24 KWh"],
          ["Potencia de salida",   "5 – 10 KW"],
          ["Instalación & Conectividad", "__section__"],
          ["Tipo",                 "LiFePO4 · Wall-Mounted"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Instalación",          "Empotrado en pared"],
          ["Protección",           "IP54"],
          ["Display",              "LCD + CAN Option"],
          ["Comunicación",         "CAN · RS485"],
          ["Rendimiento & General", "__section__"],
          ["Ciclos de vida",       "≥ 6,000 ciclos"],
          ["Dimensiones",          "530 × 480 × 165 mm"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 empotrada en pared (PowerWall) disponible en 24V y 51.2V con capacidades desde 5KWh hasta 30KWh. Diseñada para instalación residencial y comercial en sistemas solares off-grid e híbridos. Carcasa metálica IP54, display LCD, comunicación CAN/RS485 compatible con los principales inversores del mercado.",
      },
      {
        id:      "bateria-movil",
        name:    "Batería Móvil LiFePO4 48V",
        badge:   "Floor Type",
        tagline: "48V / 51.2V · 5 – 30 KWh · Off-grid & Híbrido · Con ruedas",
        img:     "/productos/lifepo4/bateria-movil/2.avif",
        imgL:    "/productos/lifepo4/bateria-movil/2.avif",
        images:  ["/productos/lifepo4/bateria-movil/2.avif", "/productos/lifepo4/bateria-movil/1.avif", "/productos/lifepo4/bateria-movil/3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil LiFePO4 48V",
        specs: [
          ["Capacidad & Energía", "__section__"],
          ["Tipo de batería",      "LiFePO4 · Floor Type (con ruedas)"],
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 400Ah · 600Ah"],
          ["Energía disponible",   "5 / 10 / 15 / 20 / 30 KWh"],
          ["Potencia de salida",   "10 – 20 KW"],
          ["Conectividad", "__section__"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Comunicación",         "CAN · RS-232 · RS485"],
          ["Display",              "LCD + CAN Option"],
          ["BMS / Bluetooth",      "Integrado"],
          ["Protección",           "IP54"],
          ["Rendimiento & General", "__section__"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Aplicación",           "Home Solar Energy System"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 de piso con ruedas, diseñada para movilidad y fácil instalación en hogares y comercios. Disponible en 48V/51.2V con capacidades de 5KWh a 30KWh. Compatible con sistemas solares off-grid e híbridos de 10–20KW. BMS integrado con Bluetooth, display LCD, comunicación CAN/RS485. Ideal como almacenamiento de energía solar con máxima flexibilidad de ubicación.",
      },
      {
        id:      "bateria-movil-mini",
        name:    "Batería Móvil Mini LiFePO4",
        badge:   "Mobile",
        tagline: "48V / 51.2V · 100 / 200 / 300 Ah · Compacta con ruedas",
        img:     "/productos/lifepo4/bateria-movil-mini/2.avif",
        imgL:    "/productos/lifepo4/bateria-movil-mini/2.avif",
        images:  ["/productos/lifepo4/bateria-movil-mini/2.avif", "/productos/lifepo4/bateria-movil-mini/1.avif", "/productos/lifepo4/bateria-movil-mini/3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil Mini LiFePO4",
        specs: [
          ["Capacidad & Energía", "__section__"],
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 320Ah"],
          ["Energía nominal",      "4.8 / 5.12 / 9.6 / 10.24 / 14.4 / 15.36 KWh"],
          ["Tipo",                 "Mobile LiFePO4 (con ruedas)"],
          ["BMS",                  "Smart BMS integrado"],
          ["Física", "__section__"],
          ["Dimensiones",          "700 × 490 × 170 mm"],
          ["Peso",                 "47 kg"],
          ["Conectividad", "__section__"],
          ["Comunicación",         "RS485 · CAN · WiFi · Bluetooth"],
          ["Display",              "LCD + CAN Option"],
          ["Rendimiento & General", "__section__"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Temp. operación",      "-20 °C a 60 °C"],
          ["Temp. almacenamiento", "-10 °C a 50 °C"],
          ["Aplicaciones",         "Solar · UPS · Marina · Silla eléctrica · Herramientas"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Versión compacta de la batería móvil LiFePO4, con formato horizontal tipo maleta y ruedas para fácil traslado. Disponible en 48V/51.2V con capacidades de 100Ah a 300Ah (4.8–15.36KWh). Smart BMS integrado con protección completa, WiFi y Bluetooth. Compatible con los principales inversores del mercado. Ideal para uso residencial, UPS, marina y movilidad eléctrica.",
      },
    ],
  },
  {
    id: "solar",
    label: "Energía Solar",
    icon: "☀️",
    items: [
      {
        id:      "paneles",
        name:    "Paneles Solares SAIRIFO",
        badge:   "Paneles Solares",
        tagline: "SAIRIFO · Monocristalino · Alta eficiencia · Watts según modelo",
        img:     "/productos/solar/paneles/1.avif",
        imgL:    "/productos/solar/paneles/1.avif",
        images:  ["/productos/solar/paneles/1.avif", "/productos/solar/paneles/2.avif", "/productos/solar/paneles/3.avif", "/productos/solar/paneles/4.avif"],
        waMsg:   "Quiero cotizar paneles solares SAIRIFO Monocristalino",
        specs: [
          ["General", "__section__"],
          ["Marca",                 "SAIRIFO"],
          ["Tipo de módulo",        "Monocristalino"],
          ["Potencias disponibles", "400W · 500W · 550W · 600W · 650W · 720W"],
          ["Eléctrico (ref. 550W)", "__section__"],
          ["Potencia máxima",       "550 WP"],
          ["Eficiencia",            "21.3 %"],
          ["Voltaje de máx. potencia (Vmp)", "41.95 VDC"],
          ["Corriente de máx. potencia (Imp)", "13.12 A"],
          ["Voltaje de circuito abierto (Voc)", "49.8 V"],
          ["Corriente de cortocircuito (Isc)", "13.98 A"],
          ["Física (ref. 550W)", "__section__"],
          ["Dimensiones",           "2278 × 1134 × 35 mm"],
          ["Peso neto",             "27.5 kg"],
          ["Materiales", "__section__"],
          ["Vidrio",                "3.2 mm High Transmission Tempered Glass"],
          ["Marco",                 "Aluminio anodizado"],
          ["Caja de juntas",        "IP68"],
          ["Conector",              "MC-4"],
        ],
        desc: "Panel solar monocristalino marca SAIRIFO disponible en potencias de 400W, 500W, 550W, 600W, 650W y 720W. El modelo de referencia 550W ofrece 21.3% de eficiencia, voltaje de circuito abierto de 49.8V y corriente de cortocircuito de 13.98A. Dimensiones de 2278×1134×35mm y 27.5kg de peso neto. Caja de juntas IP68, vidrio templado de alta transmisión y conector MC-4. Ideal para sistemas residenciales e industriales. Consulta disponibilidad de potencia por WhatsApp.",
      },
      {
        id:      "inversores",
        name:    "Inversores Híbridos TechFine",
        badge:   "Inversores Híbridos",
        tagline: "3 – 11 kW · On/Off-grid · MPPT · Onda Pura · LiFePO4 compatible",
        img:     "/productos/solar/inversores/1.avif",
        imgL:    "/productos/solar/inversores/1.avif",
        images:  ["/productos/solar/inversores/1.avif", "/productos/solar/inversores/2.avif", "/productos/solar/inversores/3.avif", "/productos/solar/inversores/4.avif"],
        waMsg:   "Quiero cotizar inversores híbridos TechFine",
        specs: [
          ["Modelos disponibles", "__section__"],
          ["3 kW",               "Ideal para hogares pequeños · Batería 24V / 48V"],
          ["5.5 kW",             "Uso residencial medio · Batería 48V"],
          ["6.2 kW",             "Residencial / comercial · Doble MPPT · Batería 48V"],
          ["11 kW",              "Comercial e industrial · Doble MPPT · Batería 48V"],
          ["Salida AC", "__section__"],
          ["Potencia nominal",   "3 / 5.5 / 6.2 / 11 kW (pico hasta 2× la nominal)"],
          ["Forma de onda",      "Onda sinusoidal pura"],
          ["Voltaje de salida",  "220 / 230 / 240 VAC ± 5%"],
          ["Frecuencia",         "50 / 60 Hz (adaptable)"],
          ["Factor de potencia", "> 0.99"],
          ["Tiempo de transferencia", "10 – 20 ms (ajustable)"],
          ["Entrada Solar (MPPT)", "__section__"],
          ["Voltaje MPPT máx.",  "500 VDC"],
          ["Rango MPPT óptimo",  "300 – 400 VDC"],
          ["Eficiencia MPPT",    "> 98%"],
          ["Entrada AC (Red)", "__section__"],
          ["Rango de voltaje",   "90 – 280 VAC (modo normal) · 170 – 280 VAC (modo UPS)"],
          ["Batería", "__section__"],
          ["Voltaje batería",    "24 VDC (modelos 3 kW) · 48 VDC (modelos 5.5 – 11 kW)"],
          ["Corriente de carga máx.", "120 – 150 A (según modelo)"],
          ["Baterías compatibles","LiFePO4 · Li-Ion · Plomo-ácido (AGM / GEL)"],
          ["Comunicación BMS",   "Auto-restart con BMS integrado"],
          ["General", "__section__"],
          ["Modos de operación", "On-grid · Off-grid · Híbrido · Sin batería"],
          ["Protecciones",       "Sobrevoltaje · Sobrecorriente · Sobretemperatura · Cortocircuito · Sobrecarga · Sobredescarga"],
          ["Conexión paralela",  "Hasta 9 unidades en paralelo (modelos GA Pro Plus)"],
          ["Comunicación",       "RS-232 · LCD táctil"],
          ["Certificaciones",    "CE · Apto para uso residencial y comercial"],
        ],
        desc: "Inversores híbridos TechFine disponibles en 3, 5.5, 6.2 y 11 kW, compatibles con sistemas solares on-grid, off-grid e híbridos. Onda sinusoidal pura con eficiencia MPPT superior al 98% y voltaje PV de hasta 500 VDC. Compatibles con baterías LiFePO4, Li-Ion y plomo-ácido, con comunicación BMS para reinicio automático. Tiempo de transferencia de red de 10–20 ms, ajustable según la aplicación. Factor de potencia > 0.99 y capacidad de operar sin batería. Los modelos de 6.2 y 11 kW cuentan con doble MPPT y soporte para conexión en paralelo de hasta 9 unidades. Ideales para hogares, comercios e instalaciones industriales en Lima y todo el Perú.",
      },
    ],
  },
  {
    id: "bms",
    label: "BMS",
    icon: "🖥️",
    items: [
      {
        id:      "dally-bms",
        name:    "Dally BMS",
        badge:   "Dally BMS",
        tagline: "Li-Ion · Puerto común con NTC · 13S / 16S · 20A / 30A / 40A",
        img:     "/productos/bms/dally/1.avif",
        imgL:    "/productos/bms/dally/1.avif",
        images:  ["/productos/bms/dally/1.avif", "/productos/bms/dally/2.avif", "/productos/bms/dally/3.avif", "/productos/bms/dally/4.avif", "/productos/bms/dally/5.avif"],
        waMsg:   "Quiero cotizar un BMS Dally",
        specs: [
          ["Modelos disponibles", "__section__"],
          ["Li-ion 13S 20A",       "13S · 54.6V carga · Puerto común · NTC incluido"],
          ["Li-ion 13S 30A",       "13S · 54.6V carga · Puerto común · NTC incluido"],
          ["Li-ion 16S 40A",       "16S · 67.2V carga · Puerto común · NTC incluido"],
          ["Compatibilidad", "__section__"],
          ["Química",              "Li-Ion NCM"],
          ["Celdas en serie",      "13S · 16S"],
          ["Puerto",               "Común (carga y descarga por el mismo terminal)"],
          ["Sensor de temperatura","NTC incluido de fábrica"],
          ["Protecciones", "__section__"],
          ["Sobrecarga por celda", "4.25V · Corte en 1s · Rearme automático"],
          ["Sobredescarga",        "2.7–2.8V · Corte en 1s · Rearme automático"],
          ["Cortocircuito",        "Respuesta 10–500 µs · Se libera al retirar carga"],
          ["Sobrecorriente carga", "Corte en 0.5s · Se libera al retirar cargador"],
          ["Alta temperatura carga","Corte a 55°C · Rearme a 50°C"],
          ["Alta temperatura desc.","Corte a 75°C · Rearme a 65–70°C"],
          ["Baja temperatura carga","-20°C · Rearme a -15°C"],
          ["Baja temperatura desc.","-40°C · Rearme a -35°C"],
          ["Balanceo pasivo",      "Activo al alcanzar voltaje de umbral por celda"],
          ["Rendimiento", "__section__"],
          ["Detección de voltaje", "Precisión ≤ ±15mV"],
          ["Detección de temp.",   "Precisión ≤ 2°C"],
          ["Resistencia interna",  "< 20 mΩ (circuito principal)"],
          ["Autoconsumo",          "< 400 µA en operación"],
          ["Temp. de operación",   "-40°C a 85°C"],
          ["Humedad relativa",     "5% – 90% RH"],
          ["General", "__section__"],
          ["Fabricante",           "Dongguan Daly Electronics Co., Ltd"],
          ["Aplicaciones",         "E-bikes · Motos eléctricas · Scooters · Packs Li-Ion a medida"],
          ["Garantía",             "1 año"],
        ],
        desc: "BMS Dally de puerto común con sensor NTC integrado, diseñado por Dongguan Daly Electronics — uno de los fabricantes de BMS más reconocidos del mercado. Disponible en tres modelos: 13S 20A, 13S 30A y 16S 40A, todos compatibles con baterías Li-Ion NCM. Carcasa sellada por inyección que mejora la resistencia a la humedad y la oxidación de componentes. Protección completa contra sobrecarga, sobredescarga, cortocircuito (respuesta en 10–500 µs), sobrecorriente y temperatura (carga hasta 55°C, descarga hasta 75°C). Balanceo pasivo por celda integrado. Precisión de medición de voltaje ≤ ±15mV. Ideal para fabricación de packs de e-bikes, motos eléctricas y scooters.",
      },
      {
        id:      "tdt-bms",
        name:    "TDT BMS",
        badge:   "TDT BMS",
        tagline: "Smart BMS · LiFePO4 & Li-Ion · Alta corriente · RS485 / CAN",
        img:     "/productos/bms/tdt/1.avif",
        imgL:    "/productos/bms/tdt/1.avif",
        images:  ["/productos/bms/tdt/1.avif", "/productos/bms/tdt/2.avif", "/productos/bms/tdt/3.avif", "/productos/bms/tdt/4.avif"],
        waMsg:   "Quiero cotizar un BMS TDT",
        specs: [
          ["Serie 14S — 50.4V nominal / 59V máx.", "__section__"],
          ["TDT-9069",  "14S · 50.4V / 59V · 60A"],
          ["TDT-8986",  "14S · 50.4V / 59V · 40A"],
          ["TDT-8986",  "14S · 50.4V / 59V · 30A"],
          ["TDT-8975",  "14S · 50.4V / 59V · 20A"],
          ["TDT-8975",  "14S · 50.4V / 59V · 10A"],
          ["Serie 10S — 36.0V nominal / 42V máx.", "__section__"],
          ["TDT-9026",  "10S · 36.0V / 42V · 60A"],
          ["TDT-8986",  "10S · 36.0V / 42V · 40A"],
          ["TDT-9025",  "10S · 36.0V / 42V · 30A"],
          ["TDT-9141",  "10S · 36.0V / 42V · 20A"],
          ["TDT-8625",  "10S · 36.0V / 42V · 10A"],
          ["Serie 7S — 25.2V nominal / 29V máx.", "__section__"],
          ["TDT-9028",  "7S · 25.2V / 29V · 60A"],
          ["TDT-8986",  "7S · 25.2V / 29V · 40A"],
          ["TDT-9025",  "7S · 25.2V / 29V · 30A"],
          ["TDT-9041",  "7S · 25.2V / 29V · 20A"],
          ["Serie 4S — 14.4V nominal / 17V máx.", "__section__"],
          ["TDT-8930",  "4S · 14.4V / 17V · 30A"],
          ["TDT-8930",  "4S · 14.4V / 17V · 20A"],
          ["TDT-8181",  "4S · 14.4V / 17V · 10A"],
          ["General", "__section__"],
          ["Aplicaciones",  "E-bikes · Scooters · Motos · Packs Li-Ion"],
          ["Garantía",      "1 año"],
        ],
        desc: "BMS TDT disponible en cuatro series: 14S (50.4V), 10S (36V), 7S (25.2V) y 4S (14.4V), con corrientes de 10A a 60A según modelo. Compatible con baterías Li-Ion NCM y LiFePO4. Diseño de pistas de alta corriente en proceso de sellado por inyección que mejora la resistencia a la humedad y prolonga la vida útil. Protección completa: sobrecarga (corte en 1s), sobredescarga (corte en 1s), sobrecorriente de carga y descarga, y cortocircuito con respuesta de 10–500 µs. Protección térmica activa: corte de carga a 55°C y de descarga a 75°C; resistente a temperaturas de operación de -40°C a 85°C. Función de balanceo pasivo por celda integrada. Precisión de detección de voltaje ≤ ±15mV y temperatura ≤ 2°C. Resistencia interna del circuito principal < 20 mΩ y autoconsumo < 400 µA. Ideal para packs de e-bikes, scooters, motos eléctricas y sistemas de almacenamiento Li-Ion.",
      },
    ],
  },
  {
    id: "baterias",
    label: "Celdas de Litio",
    icon: "🔋",
    items: [
      {
        id:      "18650",
        name:    "Celda de Litio 18650",
        badge:   "Li-Ion NCM",
        tagline: "2,550 mAh · 3.6 V · EVE · 1,000 ciclos",
        img:     "/productos/celdas/18650/1.avif",
        imgL:    "/productos/celdas/18650/1.avif",
        images:  ["/productos/celdas/18650/1.avif", "/productos/celdas/18650/2.avif"],
        waMsg:   "Quiero cotizar celdas de litio 18650 EVE",
        specs: [
          ["Eléctrico", "__section__"],
          ["Modelo",               "EVE 18650 26V"],
          ["Capacidad nominal",    "2,550 mAh"],
          ["Voltaje nominal",      "3.6 V"],
          ["Energía por celda",    "9.18 Wh"],
          ["Cátodo",               "NCM (Níquel Cobalto Manganeso)"],
          ["Tipo",                 "Li-Ion líquido recargable"],
          ["Ciclos de vida",       "≥ 1,000 ciclos"],
          ["Física", "__section__"],
          ["Dimensiones",          "Ø 18 mm × 65 mm"],
          ["Peso",                 "45 ± 2 g"],
          ["Temp. operación",      "0 °C a 45 °C"],
          ["General", "__section__"],
          ["Aplicaciones",         "E-bikes · Scooters · Vehículos eléctricos · Solar · UPS · Montacargas"],
          ["Certificaciones",      "MSDS · CE · RoHS"],
        ],
        desc: "Celda cilíndrica 18650 de EVE Energy, marca Tier-1 de Guangdong, China. Con 2,550 mAh y química NCM ofrece alta densidad de energía para aplicaciones de movilidad eléctrica, herramientas de potencia y sistemas de almacenamiento solar. 1,000 ciclos de vida garantizados con prueba de capacidad verificable.",
      },
      {
        id:      "21700",
        name:    "Celdas de Litio 21700",
        badge:   "Li-Ion NCM",
        tagline: "5,000 mAh · 3.6 V · EVE · 18.25 Wh",
        img:     "/productos/celdas/21700/1.avif",
        imgL:    "/productos/celdas/21700/1.avif",
        images:  ["/productos/celdas/21700/1.avif", "/productos/celdas/21700/2.avif"],
        waMsg:   "Quiero cotizar celdas de litio 21700 EVE",
        specs: [
          ["Eléctrico", "__section__"],
          ["Modelo",              "EVE 21700 50E"],
          ["Capacidad nominal",   "5,000 mAh"],
          ["Voltaje nominal",     "3.6 V"],
          ["Energía por celda",   "18.25 Wh"],
          ["Cátodo / Ánodo",      "NCM"],
          ["Tipo",                "Li-Ion líquido recargable"],
          ["Ciclos de vida",      "≥ 1,000 ciclos"],
          ["Física", "__section__"],
          ["Peso",                "69 g"],
          ["Temp. operación",     "0 °C a 45 °C"],
          ["General", "__section__"],
          ["Aplicaciones",        "E-bikes · Scooters · Vehículos · Solar · UPS · Herramientas · Marina"],
          ["Certificaciones",     "CE · RoHS · UN38.3"],
        ],
        desc: "Celda cilíndrica 21700 de EVE Energy con 5,000mAh y química NCM. Mayor capacidad y densidad energética que la 18650, con 18.25Wh por celda. Ideal para packs de e-bikes de alto rendimiento, motos eléctricas, herramientas de potencia y sistemas de almacenamiento portátil. 1,000 ciclos de vida garantizados.",
      },
      {
        id:      "33140",
        name:    "Celdas LiFePO4 33140",
        badge:   "LiFePO4",
        tagline: "15,000 mAh · 3.2 V · 3,000 ciclos",
        img:     "/productos/celdas/33140/3.avif",
        imgL:    "/productos/celdas/33140/3.avif",
        images:  ["/productos/celdas/33140/3.avif", "/productos/celdas/33140/1.avif", "/productos/celdas/33140/2.avif", "/productos/celdas/33140/4.avif"],
        waMsg:   "Quiero cotizar celdas LiFePO4 33140",
        specs: [
          ["Eléctrico", "__section__"],
          ["Modelo",              "33140 — 3.2V 15Ah"],
          ["Capacidad nominal",   "15,000 mAh (15 Ah)"],
          ["Voltaje nominal",     "3.2 V"],
          ["Cátodo",              "LiFePO4 (Fosfato de Hierro Litio)"],
          ["Tipo",                "Solid State"],
          ["Ciclos de vida",      "≥ 3,000 ciclos"],
          ["Física", "__section__"],
          ["Dimensiones",         "33 × 140 mm"],
          ["Peso",                "270 g"],
          ["Temp. operación",     "-22 °C a 45 °C"],
          ["General", "__section__"],
          ["Aplicaciones",        "E-bikes · Scooters · Solar · UPS · Marina · Drones · Montacargas"],
          ["Garantía",            "1 año"],
        ],
        desc: "Celda cilíndrica LiFePO4 formato 33140 con 15Ah y química de fosfato de hierro litio. Ofrece 3,000 ciclos de vida, alta estabilidad térmica y cero riesgo de ignición espontánea. Ideal para packs de motos eléctricas, triciclos de carga, sistemas solares y aplicaciones que requieren alta corriente de descarga.",
      },
      {
        id:      "prismatica",
        name:    "Celdas LiFePO4 Prismáticas EVE",
        badge:   "LiFePO4 Prismatic",
        tagline: "102 – 314 Ah · 3.2 V · 4,000 – 8,000 ciclos · Grado A",
        img:     "/productos/celdas/prismatica/1.avif",
        imgL:    "/productos/celdas/prismatica/1.avif",
        images:  ["/productos/celdas/prismatica/1.avif", "/productos/celdas/prismatica/2.avif", "/productos/celdas/prismatica/3.avif", "/productos/celdas/prismatica/4.avif", "/productos/celdas/prismatica/5.avif", "/productos/celdas/prismatica/6.avif"],
        waMsg:   "Quiero cotizar celdas LiFePO4 prismáticas EVE",
        specs: [
          ["Eléctrico", "__section__"],
          ["Modelos disponibles",     "102Ah · 105Ah · 150Ah · 230Ah · 280Ah · 304Ah · 314Ah"],
          ["Voltaje nominal",         "3.2 V por celda"],
          ["Cátodo",                  "LiFePO4 (Fosfato de Hierro Litio)"],
          ["Grado",                   "A — Full Certification CE / DE / EU"],
          ["Ciclos de vida",          "4,000 – 8,000+ ciclos (según modelo)"],
          ["Carga/descarga cont.",    "1C / 1C · Pulso: 2C / 2C"],
          ["Física", "__section__"],
          ["Peso por celda",          "~1.98 kg (102Ah) – ~5.42 kg (314Ah)"],
          ["Temp. descarga",          "-30 °C a 60 °C (según modelo)"],
          ["Temp. carga",             "0 °C a 55 °C"],
          ["Temp. almacenamiento",    "0 °C a 35 °C"],
          ["General", "__section__"],
          ["Aplicaciones",            "Solar · UPS · Marina · Montacargas · Vehículos eléctricos"],
          ["Certificaciones",         "CE · IEC · UN38.3"],
        ],
        desc: "Gama completa de celdas LiFePO4 prismáticas EVE Energy Grado A, desde 102Ah hasta 314Ah. Los modelos de mayor capacidad (280Ah / 314Ah) alcanzan 8,000+ ciclos, ideales para sistemas de almacenamiento solar residencial e industrial. Las celdas 102Ah y 105Ah ofrecen 5,000 ciclos para packs de alta densidad. Todas con certificación CE/DE/EU y BMS compatible.",
      },
    ],
  },
  {
    id: "materiales",
    label: "Materiales de Fabricación",
    icon: "🔩",
    items: [
      {
        id:      "barley-paper",
        name:    "Barley Paper",
        badge:   "Aislamiento",
        tagline: "Papel aislante bicapa · Verde/Blanco · Para packs de litio",
        img:     "/productos/materiales/barley-paper/1.avif",
        imgL:    "/productos/materiales/barley-paper/1.avif",
        images:  ["/productos/materiales/barley-paper/1.avif", "/productos/materiales/barley-paper/2.avif", "/productos/materiales/barley-paper/3.avif"],
        waMsg:   "Quiero cotizar Barley Paper (papel aislante para packs de batería)",
        specs: [
          ["Material & Construcción", "__section__"],
          ["Material",            "Papel aislante bicapa (verde exterior · blanco interior)"],
          ["Función",             "Aislamiento del cuerpo del pack · Barrera eléctrica entre celdas y carcasa"],
          ["Formato",             "Rollo continuo · Cortable a medida"],
          ["Aplicaciones", "__section__"],
          ["Uso principal",       "Fabricación de packs Li-Ion y LiFePO4"],
          ["Compatible con",      "Celdas 18650 · 21700 · 26650 · 33140 · Prismáticas"],
          ["Proceso",             "Envoltura exterior del pack · Separación interna de grupos de celdas"],
        ],
        desc: "Papel aislante bicapa (Barley Paper) en rollo, con capa exterior verde y base blanca, empleado en la fabricación profesional de packs de baterías de litio. Proporciona aislamiento eléctrico entre las celdas y la carcasa, evitando cortocircuitos accidentales. Se corta a medida para adaptarse a cualquier geometría de pack. Indispensable en la fabricación de packs 18650, 21700 y prismáticos.",
      },
      {
        id:      "barley-rings",
        name:    "Barley Rings",
        badge:   "Aislamiento",
        tagline: "Anillos aislantes para terminales de celda · 18650 / 21700 · Pack x100",
        img:     "/productos/materiales/barley-rings/1.avif",
        imgL:    "/productos/materiales/barley-rings/1.avif",
        images:  ["/productos/materiales/barley-rings/1.avif", "/productos/materiales/barley-rings/2.avif"],
        waMsg:   "Quiero cotizar Barley Rings (anillos aislantes para celdas)",
        specs: [
          ["Material & Diseño", "__section__"],
          ["Material",          "Papel aislante verde (Barley Paper troquelado)"],
          ["Forma",             "Anillo circular con orificio central"],
          ["Función",           "Aislamiento del terminal positivo de la celda · Prevención de cortocircuito por soldadura"],
          ["Compatibilidad", "__section__"],
          ["Formatos de celda", "18650 · 21700"],
          ["Uso",               "Se coloca sobre el polo positivo antes de la soldadura de punto"],
          ["Presentación",      "Pack × 100 unidades"],
        ],
        desc: "Anillos aislantes troquelados (Barley Rings) para proteger el terminal positivo de celdas 18650 y 21700 durante el proceso de soldadura de punto. Evitan que la tira de níquel haga contacto eléctrico con el lateral de la celda, eliminando el riesgo de cortocircuito interno. Material Barley Paper verde de alta resistencia dieléctrica. Presentación en pack de 100 unidades.",
      },
      {
        id:      "cinta-fibra-vidrio",
        name:    "Cinta de Fibra de Vidrio",
        badge:   "Refuerzo",
        tagline: "Cinta reforzada con fibra · Alta resistencia · Para packs de batería",
        img:     "/productos/materiales/cinta-fibra-vidrio/1.avif",
        imgL:    "/productos/materiales/cinta-fibra-vidrio/1.avif",
        images:  ["/productos/materiales/cinta-fibra-vidrio/1.avif", "/productos/materiales/cinta-fibra-vidrio/2.avif"],
        waMsg:   "Quiero cotizar cinta de fibra de vidrio para packs de batería",
        specs: [
          ["Material & Propiedades", "__section__"],
          ["Material",           "Cinta adhesiva reforzada con fibra de vidrio (filamento)"],
          ["Color",              "Transparente / Crema"],
          ["Resistencia",        "Alta resistencia a la tracción y al desgarro"],
          ["Aplicaciones", "__section__"],
          ["Uso principal",      "Refuerzo estructural de packs de batería · Fijación de grupos de celdas"],
          ["Compatible con",     "Packs 18650 · 21700 · Prismáticos · Cualquier geometría"],
          ["Proceso",            "Se aplica sobre el Barley Paper para dar rigidez y cohesión al pack"],
        ],
        desc: "Cinta adhesiva de fibra de vidrio (filamento tape) en rollo, transparente, de alta resistencia mecánica. Se utiliza en la fabricación de packs de baterías para reforzar estructuralmente el conjunto de celdas y fijarlo antes del encintado final con PVC termocontraíble. Su resistencia a la tracción superior a la cinta convencional garantiza que el pack mantenga su forma bajo vibración y temperatura.",
      },
      {
        id:      "cinta-high-temp",
        name:    "Cinta de Poliimida",
        badge:   "Alta Temperatura",
        tagline: "Cinta de poliimida · Resistente al calor · Protección durante soldadura de punto",
        img:     "/productos/materiales/cinta-high-temp/1.jpeg",
        imgL:    "/productos/materiales/cinta-high-temp/1.jpeg",
        images:  ["/productos/materiales/cinta-high-temp/1.jpeg", "/productos/materiales/cinta-high-temp/2.jpeg"],
        waMsg:   "Quiero cotizar cinta de poliimida para fabricación de baterías",
        specs: [
          ["Material & Propiedades", "__section__"],
          ["Material",           "Poliimida con adhesivo de silicona"],
          ["Marca",              "Sin marca"],
          ["Color",              "Naranja / Ámbar"],
          ["Resistencia térmica","Hasta 200 °C continuo · Picos cortos hasta 260 °C"],
          ["Aislamiento",        "Dieléctrico · Resistente a solventes y ácidos"],
          ["Aplicaciones", "__section__"],
          ["Uso principal",      "Protección durante soldadura de punto · Aislamiento térmico de BMS y cables"],
          ["Uso secundario",     "Fijación de termistores NTC · Sellado de conexiones en el pack"],
          ["Compatible con",     "Todos los formatos de celda cilíndrica y prismática"],
        ],
        desc: "Cinta de poliimida color naranja, resistente a temperaturas de hasta 200°C continuos. Sin marca, con adhesivo de silicona que no deja residuo y mantiene sus propiedades en un amplio rango de temperatura. Imprescindible en la fabricación de packs de baterías para proteger zonas sensibles durante la soldadura de punto, aislar térmicamente el BMS y fijar termistores NTC. Corte limpio y fácil aplicación.",
      },
      {
        id:      "conectores-xt60",
        name:    "Conectores XT60",
        badge:   "Conectores",
        tagline: "Par macho + hembra · 60A · Para packs de litio · E-bikes · RC",
        img:     "/productos/materiales/conectores-xt60/1.jpeg",
        imgL:    "/productos/materiales/conectores-xt60/1.jpeg",
        images:  ["/productos/materiales/conectores-xt60/1.jpeg", "/productos/materiales/conectores-xt60/2.jpeg", "/productos/materiales/conectores-xt60/3.jpeg"],
        waMsg:   "Quiero cotizar conectores XT60 para pack de batería",
        specs: [
          ["Eléctrico", "__section__"],
          ["Corriente nominal",  "60 A"],
          ["Corriente pico",     "90 A (pulso corto)"],
          ["Voltaje máx.",       "500 V"],
          ["Resistencia interna","< 0.5 mΩ"],
          ["Físico", "__section__"],
          ["Color",              "Amarillo (cuerpo nylon)"],
          ["Tipo",               "Par macho + hembra (XT60-M + XT60-F)"],
          ["Sección de cable",   "12–10 AWG recomendado"],
          ["Aplicaciones", "__section__"],
          ["Uso principal",      "Salida de packs de batería · E-bikes · Motos · Scooters"],
          ["Uso secundario",     "Sistemas solares · UPS · RC vehicles"],
          ["Presentación",       "Unidad o bolsas a granel disponibles"],
        ],
        desc: "Conector XT60 estándar de la industria para conexión de packs de baterías de litio. Diseño de par macho+hembra con cuerpo de nylon resistente al calor y contactos de cobre estañado. Corriente nominal de 60A con picos de 90A. Ampliamente utilizado en e-bikes, motos eléctricas, scooters, vehículos RC y sistemas solares. Fácil soldadura con estaño estándar, bajo par resistivo y conexión segura sin posibilidad de inversión de polaridad.",
      },
      {
        id:      "holders",
        name:    "Holders para Celdas 18650",
        badge:   "Soportes",
        tagline: "Soportes plásticos · Tipo panal y tipo lineal · Solo 18650 · Alineación de celdas",
        img:     "/productos/materiales/holders/1.jpeg",
        imgL:    "/productos/materiales/holders/1.jpeg",
        images:  ["/productos/materiales/holders/1.jpeg", "/productos/materiales/holders/2.jpeg", "/productos/materiales/holders/3.jpeg"],
        waMsg:   "Quiero cotizar holders para celdas 18650 (tipo panal o tipo lineal)",
        specs: [
          ["Modelos disponibles", "__section__"],
          ["Tipo panal (Honeycomb)", "Grid hexagonal — máxima densidad de celdas por área"],
          ["Tipo lineal",           "Soportes en fila horizontal — ideal para configuraciones planas"],
          ["Material & Construcción", "__section__"],
          ["Material",          "Plástico ABS resistente al calor"],
          ["Color",             "Negro"],
          ["Compatibilidad", "__section__"],
          ["Formatos de celda", "18650 (exclusivo)"],
          ["Función",           "Alineación precisa · Separación eléctrica · Canales de ventilación entre celdas"],
          ["Proceso", "__section__"],
          ["Uso",               "Se monta entre capas de celdas antes de la soldadura de punto"],
          ["Beneficio",         "Elimina movimiento bajo vibración · Reduce riesgo de cortocircuito interno"],
          ["Cortable",          "Sí — adaptable a cualquier configuración S/P"],
        ],
        desc: "Soportes de plástico para celdas 18650, disponibles en dos modelos: tipo panal (honeycomb) con estructura hexagonal de máxima densidad, y tipo lineal con disposición en fila horizontal, ideal para packs de perfil plano. Ambos modelos mantienen las celdas perfectamente alineadas y separadas, garantizando un espaciado uniforme para la soldadura de punto y canales de ventilación para control térmico. Cortables a medida para adaptarse a cualquier configuración de series y paralelos.",
      },
      {
        id:      "indicadores-voltaje",
        name:    "Indicadores de Voltaje",
        badge:   "Medidor de Voltaje",
        tagline: "12 – 72 V · Display LED · Azul / Rojo · Normal y resistente al agua",
        img:     "/productos/materiales/indicadores-voltaje/1.avif",
        imgL:    "/productos/materiales/indicadores-voltaje/1.avif",
        images:  ["/productos/materiales/indicadores-voltaje/1.avif", "/productos/materiales/indicadores-voltaje/2.avif", "/productos/materiales/indicadores-voltaje/3.avif", "/productos/materiales/indicadores-voltaje/4.avif", "/productos/materiales/indicadores-voltaje/5.avif"],
        waMsg:   "Quiero cotizar indicadores de voltaje para pack de batería",
        specs: [
          ["Especificaciones", "__section__"],
          ["Rango de voltaje",   "12 V – 72 V"],
          ["Tipo de display",    "LED digital"],
          ["Colores disponibles","Azul · Rojo"],
          ["Modelos", "__section__"],
          ["Normal",             "Para instalación interior o en carcasa protegida"],
          ["Resistente al agua", "Sellado — apto para exposición a humedad y lluvia"],
          ["Instalación", "__section__"],
          ["Tipo de montaje",    "Empotrado en carcasa del pack · Panel frontal"],
          ["Conexión",           "2 cables (V+ / V−) directos al pack"],
          ["Aplicaciones",       "E-bikes · Scooters · Motos eléctricas · Solar · UPS"],
        ],
        desc: "Indicador de voltaje con display LED digital, compatible con packs de 12V a 72V. Disponible en color azul o rojo, y en dos versiones: normal para instalación en carcasa y resistente al agua para montaje exterior expuesto a humedad. Conexión directa al pack con dos cables. Permite monitorear el nivel de carga del pack de forma visual en tiempo real. Ideal para e-bikes, motos eléctricas, scooters y cualquier pack de litio.",
      },
      {
        id:      "nickel-plated",
        name:    "Nickel Steel Plated",
        badge:   "Soldadura",
        tagline: "Tiras de acero niquelado · 0.10 mm y 0.15 mm · Hasta 12 celdas 18650 · RoHS",
        img:     "/productos/materiales/nickel-plated/1.jpeg",
        imgL:    "/productos/materiales/nickel-plated/1.jpeg",
        images:  ["/productos/materiales/nickel-plated/1.jpeg", "/productos/materiales/nickel-plated/2.jpeg", "/productos/materiales/nickel-plated/3.jpeg", "/productos/materiales/nickel-plated/4.jpeg", "/productos/materiales/nickel-plated/5.jpeg"],
        waMsg:   "Quiero cotizar tiras nickel steel plated para soldadura de punto",
        specs: [
          ["Material & Composición", "__section__"],
          ["Material",           "Acero con recubrimiento de níquel puro"],
          ["Certificación",      "RoHS"],
          ["Espesores disponibles","0.10 mm · 0.15 mm"],
          ["Ancho",              "Universal — cubre hasta 12 celdas 18650 en paralelo"],
          ["Uso en fabricación", "__section__"],
          ["Proceso",            "Soldadura de punto neumática o transistorizada"],
          ["Función",            "Conexión eléctrica entre celdas en serie y paralelo"],
          ["Compatible con",     "Celdas 18650"],
          ["Selección de espesor","__section__"],
          ["0.10 mm",            "Packs de menor corriente · Conexiones de bajo amperaje"],
          ["0.15 mm",            "Packs de mayor corriente · Mayor conductividad y resistencia mecánica"],
        ],
        desc: "Tiras de acero con recubrimiento de níquel puro (Nickel Steel Plated) para soldadura de punto en fabricación de packs de baterías 18650. Disponibles en espesores de 0.10mm y 0.15mm, con ancho universal que cubre hasta 12 celdas en paralelo. Ofrecen buena conductividad eléctrica, resistencia a la oxidación y facilidad de soldadura. Certificadas RoHS.",
      },
      {
        id:      "pvc-termocontraible",
        name:    "PVC Termocontraíble",
        badge:   "Sellado de Pack",
        tagline: "No.9 · Diámetro plegado 350 mm · Azul · Sellado y protección de packs",
        img:     "/productos/materiales/pvc-termocontraible/1.jpeg",
        imgL:    "/productos/materiales/pvc-termocontraible/1.jpeg",
        images:  ["/productos/materiales/pvc-termocontraible/1.jpeg", "/productos/materiales/pvc-termocontraible/2.jpeg"],
        waMsg:   "Quiero cotizar PVC termocontraíble para pack de batería",
        specs: [
          ["Especificaciones", "__section__"],
          ["Nombre técnico",     "PVC Heat Shrink Tube No.9"],
          ["Diámetro plegado",   "350 mm (diámetro expandido aprox. 222 mm)"],
          ["Color",              "Azul"],
          ["Relación de contracción","2:1"],
          ["Temperatura de contracción","90 – 120 °C"],
          ["Aplicaciones", "__section__"],
          ["Uso principal",      "Cubierta exterior y sellado de packs de batería de litio"],
          ["Uso secundario",     "Protección mecánica y aislamiento eléctrico adicional"],
          ["Presentación", "__section__"],
          ["Formato",            "Rollo continuo · Cortable a medida"],
          ["Compatible con",     "Packs 18650 de cualquier configuración S/P"],
        ],
        desc: "Tubo de PVC termocontraíble No.9, color azul, con diámetro plegado de 350mm (diámetro expandido aproximado 222mm). Diseñado para el sellado y acabado exterior de packs de baterías de litio 18650. Con relación de contracción 2:1, se adapta al pack al aplicar calor, proporcionando protección mecánica, aislamiento eléctrico adicional y un acabado limpio y profesional.",
      },
    ],
  },
];

export const SERVICES = [
  {
    id: "fabricacion",
    label: "Fabricación",
    icon: "⚙️",
    items: [
      {
        id:      "fab-pack",
        name:    "Fabricación de Pack de Batería",
        badge:   "A medida",
        tagline: "Li-Ion · LiFePO4 · Cualquier voltaje y capacidad · Informe técnico incluido",
        img:     "/servicios/fabricacion/fab-pack/0.jpg",
        imgL:    "/servicios/fabricacion/fab-pack/0.jpg",
        images:  ["/servicios/fabricacion/fab-pack/0.jpg","/servicios/fabricacion/fab-pack/1.avif","/servicios/fabricacion/fab-pack/2.avif","/servicios/fabricacion/fab-pack/3.avif","/servicios/fabricacion/fab-pack/4.avif","/servicios/fabricacion/fab-pack/5.avif","/servicios/fabricacion/fab-pack/6.avif","/servicios/fabricacion/fab-pack/7.avif","/servicios/fabricacion/fab-pack/8.avif","/servicios/fabricacion/fab-pack/9.avif","/servicios/fabricacion/fab-pack/10.avif"],
        waMsg:   "Hola, quiero información sobre fabricación de pack de batería a medida",
        specs: [
          ["Parámetros del pack", "__section__"],
          ["Químicas disponibles",   "Li-Ion NCM (18650/21700) · LiFePO4 (32700/prismática)"],
          ["Voltajes",               "12V · 24V · 36V · 48V · 60V · 72V · custom"],
          ["Capacidades",            "Desde 5Ah hasta proyectos de gran escala"],
          ["Ejemplo fabricado",      "60V 12.5Ah — 16S5P · 80 celdas EVE ICR18650 · 720 Wh"],
          ["Proceso de ensamblaje", "__section__"],
          ["Verificación de celdas", "Voltaje + impedancia interna + capacidad celda a celda"],
          ["Soportes",               "Honeycomb holders (alineación y separación)"],
          ["Ensamblaje",             "Soldadura por puntos neumática · níquel 0.15 mm"],
          ["Aislamiento",            "Triple: papel antiestático · cinta térmica · fibra de vidrio"],
          ["Configuración de celdas","Series y paralelo a medida del proyecto"],
          ["BMS & Calidad", "__section__"],
          ["BMS integrado",          "Protección: sobrecarga · sobredescarga · cortocircuito · balanceo"],
          ["Balance garantizado",    "ΔV entre grupos ≤ 0.02V"],
          ["Pruebas finales",        "Carga completa + descarga controlada + verificación BMS"],
          ["Acabado & Entrega", "__section__"],
          ["Carcasa",                "ABS · Aluminio · IP54/IP65 según proyecto"],
          ["Conectores",             "Anderson · XT60 · XLR · custom"],
          ["Informe técnico",        "Firmado por Ingeniero Responsable (Nº único)"],
          ["Certificado de garantía","Mínimo 1 año según proyecto"],
          ["Aplicaciones",           "E-bike · Moto eléctrica · Scooter · Solar · UPS · Marina · Industria"],
        ],
        desc: "Diseñamos y fabricamos packs de baterías de litio completamente a medida. Nuestro proceso incluye selección y verificación celda a celda (voltaje, impedancia, capacidad), ensamblaje con soportes honeycomb, soldadura por puntos neumática con níquel de alta conductividad, instalación de BMS con protecciones completas y triple aislamiento. Cada pack pasa por pruebas de carga/descarga controlada y se entrega con informe técnico numerado y certificado de garantía firmado por ingeniero responsable.",
      },
      {
        id:      "soldadura-punto",
        name:    "Soldadura de Punto Profesional",
        badge:   "Servicio",
        tagline: "Unión de tiras de níquel y cobre · Celdas 18650 / 21700 / prismáticas · Entrega en el día",
        video:   "/servicios/fabricacion/soldadura-punto/soldadura.mp4",
        img:     "/servicios/fabricacion/soldadura-punto/portada.avif",
        imgL:    "/servicios/fabricacion/soldadura-punto/portada.avif",
        waMsg:   "Hola, quiero información sobre el servicio de soldadura de punto profesional",
        specs: [
          ["¿Qué soldamos?", "__section__"],
          ["Tiras de conexión",    "Níquel puro · Níquel enchapado en acero · Cobre-níquel"],
          ["Formatos de celda",    "18650 · 21700 · 26650 · 33140 · Prismáticas"],
          ["Espesores de tira",    "0.10 mm · 0.15 mm · 0.20 mm · 0.25 mm · 0.30 mm"],
          ["Aplicaciones",         "Packs de e-bike · Motos eléctricas · Scooters · UPS · Solar · Portátiles"],
          ["¿Qué incluye el servicio?", "__section__"],
          ["Asesoría técnica",     "Recomendación del espesor y ancho de tira según la corriente del pack"],
          ["Soldadura profesional","Doble pulso transistorizado — unión firme, mínimas salpicaduras"],
          ["Control de calidad",   "Inspección visual y prueba de adherencia en cada celda"],
          ["Entrega",              "Mismo día para proyectos de hasta 100 celdas"],
          ["Capacidad & Plazos", "__section__"],
          ["Capacidad diaria",     "Hasta 500 celdas por jornada"],
          ["Pedidos especiales",   "Packs de gran escala: coordinar plazo con anticipación"],
          ["Servicio presencial",  "En nuestro taller — Chorrillos, Lima"],
          ["Información adicional", "__section__"],
          ["Apto para",            "Clientes que traen sus propias celdas y requieren soldadura"],
          ["También fabricamos",   "Pack completo a medida (ver servicio Fabricación de Pack)"],
          ["Certificado",          "Disponible para packs fabricados íntegramente por nosotros"],
        ],
        desc: "Ofrecemos soldadura de punto profesional para la fabricación y reparación de packs de baterías de litio. Utilizamos equipos de doble pulso transistorizado que garantizan uniones firmes y de alta calidad en tiras de níquel, níquel enchapado y cobre-níquel, sin dañar las celdas por exceso de calor. El servicio incluye asesoría técnica sobre el espesor y ancho de tira adecuados para la corriente de tu proyecto, soldadura con parámetros calibrados para cada material e inspección de calidad en cada punto. Compatible con celdas 18650, 21700, 26650, 33140 y prismáticas. Ideal para fabricantes de packs, talleres de reparación de e-bikes y motos eléctricas que necesitan soldadura profesional sin adquirir el equipo.",
      },
      {
        id:      "fab-conversion",
        name:    "Conversión a Litio",
        badge:   "Conversión",
        tagline: "Reemplaza plomo-ácido por litio · Sin modificar cableado ni inversor",
        video:   "/servicios/fabricacion/fab-conversion/conversion.mp4",
        img:     "/servicios/fabricacion/fab-conversion/portada.avif",
        imgL:    "/servicios/fabricacion/fab-conversion/portada.avif",
        waMsg:   "Hola, quiero información sobre conversión de batería plomo a litio",
        comparison: {
          cols: [
            { name: "LiFePO4",    recommended: true  },
            { name: "Li-Ion NCM", recommended: false },
            { name: "Plomo-ácido",recommended: false },
          ],
          rows: [
            { icon: "🔄", label: "Ciclos de vida",     vals: ["≥ 6,000",   "≥ 1,000",    "300 – 500"],   win: [0],    best: 0 },
            { icon: "⚡", label: "Eficiencia",          vals: ["> 95%",     "> 95%",      "70 – 80%"],    win: [0, 1], best: 0 },
            { icon: "⚖️", label: "Peso relativo",       vals: ["−70%",      "−65%",       "Referencia"],  win: [0, 1], best: 0 },
            { icon: "🔧", label: "Mantenimiento",       vals: ["Ninguno",   "Ninguno",    "Periódico"],   win: [0, 1], best: 0 },
            { icon: "🌡️", label: "Seguridad térmica",   vals: ["Muy alta",  "Alta",       "Media"],       win: [0],    best: 0 },
            { icon: "📅", label: "Vida útil",           vals: ["10+ años",  "3–5 años",   "1–2 años"],    win: [0],    best: 0 },
          ],
        },
        specs: [
          ["Compatibilidad", "__section__"],
          ["Reemplazo directo",    "Sin modificar cableado ni inversor existente"],
          ["Químicas disponibles", "LiFePO4 (recomendada) · Li-Ion NCM"],
          ["Voltajes",             "12V · 24V · 36V · 48V · 60V · 72V"],
          ["Proceso", "__section__"],
          ["Diagnóstico previo",   "Evaluación del sistema eléctrico sin costo"],
          ["Proceso",              "Desmontaje · reemplazo · configuración BMS · prueba de carga"],
          ["BMS incluido",         "Configurado para el cargador actual del cliente"],
          ["Entrega", "__section__"],
          ["Certificado técnico",  "Firmado por Ingeniero Responsable"],
          ["Garantía",             "1 año sobre el pack instalado"],
          ["Aplicaciones",         "Motos · Scooters · Triciclos · UPS · Solar · Marina · Montacargas"],
        ],
        desc: "Convertimos tu batería de plomo-ácido AGM/GEL a litio LiFePO4 sin tocar el cableado ni cambiar el inversor. El proceso incluye diagnóstico eléctrico del sistema, desmontaje de la batería antigua, instalación del pack de litio con BMS configurado para tu cargador actual y prueba de carga completa. El resultado: hasta 10× más ciclos de vida, >95% de eficiencia energética, hasta 70% menos peso y cero mantenimiento. Cada conversión incluye certificado técnico firmado por ingeniero responsable.",
      },
    ],
  },
  {
    id: "reparacion",
    label: "Reparación",
    icon: "🔧",
    items: [
      {
        id:      "rep-bateria",
        name:    "Reparación de Batería de Litio",
        badge:   "Reparación",
        tagline: "Diagnóstico · Reemplazo de celdas · Recertificación",
        img:     "/servicios/reparacion/baterias/1.avif",
        imgL:    "/servicios/reparacion/baterias/1.avif",
        images:  ["/servicios/reparacion/baterias/1.avif","/servicios/reparacion/baterias/2.avif","/servicios/reparacion/baterias/3.avif","/servicios/reparacion/baterias/4.avif","/servicios/reparacion/baterias/5.avif"],
        waMsg:   "Hola, quiero información sobre reparación de batería de litio",
        specs: [
          ["Diagnóstico", "__section__"],
          ["Prueba de capacidad",  "Análisis celda por celda con equipo especializado"],
          ["Tipos soportados",     "Li-Ion NCM · LiFePO4 · cualquier formato"],
          ["Reparación", "__section__"],
          ["Servicio",             "Reemplazo de celdas · BMS · conectores"],
          ["Balanceo",             "Ecualización de celdas incluida"],
          ["Entrega", "__section__"],
          ["Recertificación",      "Certificado técnico post-reparación"],
          ["Aplicaciones",         "E-bikes · Motos · Scooters · UPS · Solar"],
          ["Garantía",             "6 meses sobre el trabajo realizado"],
        ],
        desc: "Diagnóstico y reparación de packs de baterías de litio. Identificamos celdas defectuosas mediante prueba de capacidad individual, reemplazamos con celdas Grado A y recertificamos el pack. Extendemos la vida útil evitando el costo de una batería nueva.",
      },
      {
        id:      "rep-bms",
        name:    "Reemplazo de BMS",
        badge:   "BMS",
        tagline: "Diagnóstico · Reemplazo · Actualización de parámetros",
        img:     "/servicios/reparacion/bms/1.avif",
        imgL:    "/servicios/reparacion/bms/1.avif",
        images:  ["/servicios/reparacion/bms/1.avif","/servicios/reparacion/bms/2.avif","/servicios/reparacion/bms/3.avif","/servicios/reparacion/bms/4.avif"],
        waMsg:   "Hola, quiero información sobre reparación o reemplazo de BMS",
        specs: [
          ["Diagnóstico", "__section__"],
          ["Lectura de fallas",    "Análisis de parámetros y errores del BMS"],
          ["Compatibilidad",       "Li-Ion · LiFePO4 · cualquier marca"],
          ["Comunicación",         "UART · CAN · RS485 según modelo"],
          ["Reparación", "__section__"],
          ["Servicio",             "Reparación o reemplazo de BMS"],
          ["Configuración",        "Ajuste de voltaje de corte · balanceo · protecciones"],
          ["Entrega", "__section__"],
          ["Garantía",             "6 meses sobre el trabajo realizado"],
        ],
        desc: "El BMS (Battery Management System) es el cerebro del pack. Reparamos o reemplazamos BMS defectuosos y los configuramos con los parámetros correctos para tu batería. Solucionamos problemas de apagado inesperado, error de balanceo y sobreprotección.",
      },
    ],
  },
];
