export const WA_NUMBER = "51900025403";
export const WA_BASE   = `https://wa.me/${WA_NUMBER}`;
export const wm = (text = "") =>
  text ? `${WA_BASE}?text=${encodeURIComponent(text)}` : WA_BASE;

export const COMPANY = {
  name:      "Recursos Tecnológicos S.A.C.",
  phone:     "+51 900 025 403",
  email:     "recursostecnologicossac@gmail.com",
  address:   "Av. Alameda Sur 547, Chorrillos, Lima",
  address2:  "Jr. Leticia 939, Lima",
  facebook:  "https://facebook.com/rectecnologicosperu",
  instagram: "https://instagram.com/recursostecnologicos",
  hours:     "Lun–Sáb · 9am – 6pm",
};

export const TABS = [
  { id: "inicio",    label: "Inicio"    },
  { id: "productos", label: "Productos", hasMega: true },
  { id: "servicios", label: "Servicios", hasMega: true },
  { id: "asesoria",  label: "Asesoría"  },
  { id: "nosotros",  label: "Nosotros"  },
  { id: "contacto",  label: "Contacto"  },
];

const Q  = "?auto=format&fit=crop&w=700&q=82";
const QL = "?auto=format&fit=crop&w=1000&q=85";

export const PRODUCTS = [
  {
    id: "lifepo4",
    label: "Baterías LiFePO4",
    icon: "🔒",
    items: [
      {
        id:      "bateria-sellada",
        name:    "Batería Sellada 12V - 24V",
        badge:   "LiFePO4",
        tagline: "12.8 V / 25.6 V · Deep Cycle · BMS integrado",
        img:     "/productos/lifepo4/bateria-sellada/1.avif",
        imgL:    "/productos/lifepo4/bateria-sellada/1.avif",
        images:  ["/productos/lifepo4/bateria-sellada/1.avif", "/productos/lifepo4/bateria-sellada/2.avif", "/productos/lifepo4/bateria-sellada/3.avif"],
        waMsg:   "Quiero cotizar baterías LiFePO4 selladas 12V / 24V",
        specs: [
          ["Voltajes disponibles",  "12.8 V · 25.6 V"],
          ["Modelos 12V",           "6 Ah · 24 Ah · 50 Ah · 100 Ah · 200 Ah"],
          ["Energía 12V",           "76.8 / 307 / 640 / 1,280 / 2,560 Wh"],
          ["Modelos 24V",           "50 Ah · 100 Ah · 200 Ah"],
          ["Energía 24V",           "1,280 / 2,560 / 5,120 Wh"],
          ["Celda",                 "32700 LiFePO4"],
          ["Voltaje carga 12V",     "14.6 V"],
          ["Voltaje carga 24V",     "29.2 V"],
          ["Ciclos",                "≥ 6,000 (DoD 95%)"],
          ["Temp. descarga",        "-20 °C a 60 °C"],
          ["Temp. carga",           "0 °C a 45 °C"],
          ["Aplicaciones",          "Solar · UPS · Marina · Telecom · Vehículos · Alarmas"],
          ["Certificaciones",       "CE · RoHS · UN38.3"],
          ["Garantía",              "2 años"],
        ],
        desc: "Baterías LiFePO4 selladas disponibles en 12V y 24V para todo tipo de aplicación. La serie 12V va desde 6Ah (moto/UPS) hasta 200Ah para sistemas solares de gran autonomía. La serie 24V ofrece hasta 5,120 Wh en un solo módulo, ideal para inversores industriales, marina y telecomunicaciones. BMS integrado, sin mantenimiento, reemplazo directo de plomo-ácido AGM/GEL.",
      },
      {
        id:      "wall-battery",
        name:    "Batería Empotrada PowerWall LiFePO4",
        badge:   "Wall-Mounted",
        tagline: "24V / 51.2V · 5–30 KWh · Off-grid & Híbrido",
        img:     "/productos/lifepo4/wall-battery/1.avif",
        imgL:    "/productos/lifepo4/wall-battery/2.avif",
        images:  ["/productos/lifepo4/wall-battery/1.avif", "/productos/lifepo4/wall-battery/2.avif", "/productos/lifepo4/wall-battery/3.avif"],
        waMsg:   "Quiero cotizar Batería Empotrada PowerWall LiFePO4",
        specs: [
          ["Tipo de batería",      "LiFePO4"],
          ["Voltajes disponibles", "24V · 51.2V"],
          ["Capacidades 24V",      "100Ah / 200Ah / 300Ah / 400Ah / 600Ah"],
          ["Energía 24V",          "5 / 10 / 15 / 20 / 30 KWh"],
          ["Capacidades 51.2V",    "50Ah / 80Ah / 100Ah / 200Ah"],
          ["Energía 51.2V",        "2.56 / 4.1 / 5.12 / 10.24 KWh"],
          ["Potencia de salida",   "3.8 KW (24V) · 5–10 KW (51.2V)"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Tipo de instalación",  "Wall-Mounted (Empotrado en pared)"],
          ["Protección",           "IP54"],
          ["Display",              "LCD + CAN Option"],
          ["Comunicación",         "CAN · RS485"],
          ["Ciclos de vida",       "≥ 6,000 ciclos"],
          ["Dimensiones",          "530 × 480 × 165 mm"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 empotrada en pared (PowerWall) disponible en 24V y 51.2V con capacidades desde 5KWh hasta 30KWh. Diseñada para instalación residencial y comercial en sistemas solares off-grid e híbridos. Carcasa metálica IP54, display LCD, comunicación CAN/RS485 compatible con los principales inversores del mercado.",
      },
      {
        id:      "bateria-movil",
        name:    "Batería Móvil LiFePO4 48V",
        badge:   "Floor Type",
        tagline: "48V / 51.2V · 5 – 30 KWh · Off-grid & Híbrido · Con ruedas",
        img:     "/productos/lifepo4/bateria-movil/2.avif",
        imgL:    "/productos/lifepo4/bateria-movil/2.avif",
        images:  ["/productos/lifepo4/bateria-movil/2.avif", "/productos/lifepo4/bateria-movil/1.avif", "/productos/lifepo4/bateria-movil/3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil LiFePO4 48V",
        specs: [
          ["Tipo de batería",      "LiFePO4"],
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 400Ah · 600Ah"],
          ["Energía disponible",   "5 / 10 / 15 / 20 / 30 KWh"],
          ["Potencia de salida",   "10 – 20 KW"],
          ["Conexión a red",       "Off-grid · Híbrido"],
          ["Tipo",                 "Floor Type (con ruedas)"],
          ["Protección",           "IP54"],
          ["Comunicación",         "CAN · RS-232 · RS485"],
          ["Display",              "LCD + CAN Option"],
          ["BMS / Bluetooth",      "Sí"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Aplicación",           "Home Solar Energy System"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Batería LiFePO4 de piso con ruedas, diseñada para movilidad y fácil instalación en hogares y comercios. Disponible en 48V/51.2V con capacidades de 5KWh a 30KWh. Compatible con sistemas solares off-grid e híbridos de 10–20KW. BMS integrado con Bluetooth, display LCD, comunicación CAN/RS485. Ideal como almacenamiento de energía solar con máxima flexibilidad de ubicación.",
      },
      {
        id:      "bateria-movil-mini",
        name:    "Batería Móvil Mini LiFePO4",
        badge:   "Mobile",
        tagline: "48V / 51.2V · 100 / 200 / 300 Ah · Compacta con ruedas",
        img:     "/productos/lifepo4/bateria-movil-mini/2.avif",
        imgL:    "/productos/lifepo4/bateria-movil-mini/2.avif",
        images:  ["/productos/lifepo4/bateria-movil-mini/2.avif", "/productos/lifepo4/bateria-movil-mini/1.avif", "/productos/lifepo4/bateria-movil-mini/3.avif"],
        waMsg:   "Quiero cotizar Batería Móvil Mini LiFePO4",
        specs: [
          ["Voltaje nominal",      "48V / 51.2V"],
          ["Capacidades",          "100Ah · 200Ah · 300Ah · 320Ah"],
          ["Energía nominal",      "4.8 / 5.12 / 9.6 / 10.24 / 14.4 / 15.36 KWh"],
          ["Tipo",                 "Mobile LiFePO4 (con ruedas)"],
          ["BMS",                  "Smart BMS — sobredescar., sobrecarga, cortocircuito, ecualización"],
          ["Ciclos de vida",       "≥ 6,000 ciclos (@50% DoD)"],
          ["Temp. operación",      "-20 °C a 60 °C (recomendado 10–40 °C)"],
          ["Temp. almacenamiento", "-10 °C a 50 °C"],
          ["Dimensiones",          "700 × 490 × 170 mm"],
          ["Peso",                 "47 kg"],
          ["Display",              "LCD + CAN Option"],
          ["Comunicación",         "RS485 · CAN · WiFi · Bluetooth"],
          ["Aplicaciones",         "Solar · UPS · Marina · Silla eléctrica · Herramientas"],
          ["Certificaciones",      "CE · RoHS · UN38.3"],
          ["Garantía",             "2 años"],
        ],
        desc: "Versión compacta de la batería móvil LiFePO4, con formato horizontal tipo maleta y ruedas para fácil traslado. Disponible en 48V/51.2V con capacidades de 100Ah a 300Ah (4.8–15.36KWh). Smart BMS integrado con protección completa, WiFi y Bluetooth. Compatible con los principales inversores del mercado. Ideal para uso residencial, UPS, marina y movilidad eléctrica.",
      },
    ],
  },
  {
    id: "solar",
    label: "Energía Solar",
    icon: "☀️",
    items: [
      {
        id:      "paneles",
        name:    "Panel Solar Rosen RS450M-108HC",
        badge:   "N-Type TOPCON",
        tagline: "21.3 % Eficiencia · Bifacial Double Glass · Watts y peso según modelo",
        img:     "/productos/solar/paneles/1.avif",
        imgL:    "/productos/solar/paneles/1.avif",
        images:  ["/productos/solar/paneles/1.avif", "/productos/solar/paneles/2.avif", "/productos/solar/paneles/3.avif", "/productos/solar/paneles/4.avif"],
        waMsg:   "Quiero cotizar paneles solares Rosen RS450M-108HC",
        specs: [
          ["Modelo",            "RS450M-108HC"],
          ["Marca",             "Rosen / OEM"],
          ["Eficiencia",        "21.3 %"],
          ["Tipo de celda",     "N-Type TOPCON Bifacial Double Glass"],
          ["Tamaño de celda",   "210 / 182 mm"],
          ["Orientación",       "120 células (6×20)"],
          ["Dimensiones",       "1722 × 1134 × 30/35 mm"],
          ["Watts",             "Varía según modelo — consultar"],
          ["Peso",              "Varía según modelo — consultar"],
          ["Vidrio",            "3.2 mm High Transmission Tempered Glass"],
          ["Marco",             "Aluminio anodizado Silver / Black"],
          ["Caja de juntas",    "IP68"],
          ["Back sheet",        "Black / White Backsheet"],
          ["Cable",             "4 mm² PV Cable"],
          ["Conector",          "MC-4 / Male / Female / Fuse"],
          ["Certificados",      "ISO9001 / 14001 / CE / TUV"],
          ["Origen",            "Anhui, China"],
        ],
        desc: "Panel solar N-Type TOPCON Bifacial Double Glass con 21.3% de eficiencia. Tecnología de doble cara que aprovecha la radiación directa y reflejada para maximizar la generación. Marco de aluminio anodizado, caja de juntas IP68 y certificación ISO/CE/TUV. Disponible en distintas potencias y pesos — consulta por WhatsApp.",
      },
      {
        id:      "inversores",
        name:    "Inversores Híbridos On/Off-grid",
        badge:   "Inversor",
        tagline: "3 – 10 kW · MPPT integrado · WiFi",
        img:     `https://images.unsplash.com/photo-1545208075-95a3e09c1ea1${Q}`,
        imgL:    `https://images.unsplash.com/photo-1545208075-95a3e09c1ea1${QL}`,
        waMsg:   "Quiero cotizar inversores híbridos solares",
        specs: [
          ["Potencia",          "3 kW / 5 kW / 8 kW / 10 kW"],
          ["Modos",             "On-grid · Off-grid · Híbrido"],
          ["MPPT integrado",    "Eficiencia 98 %"],
          ["Voltaje de batería","48 V (100–600 V string)"],
          ["Monitoreo",         "WiFi + App móvil"],
          ["Protecciones",      "Sobrecarga · CC · temperatura"],
          ["Baterías compat.",  "LiFePO4 · Li-Ion · Plomo-ácido"],
        ],
        desc: "Inversores híbridos con conmutación automática entre red eléctrica, paneles solares y baterías, sin intervención del usuario. Monitoreo en tiempo real desde cualquier dispositivo. Compatible con baterías LiFePO4 y sistemas de hasta 3 fases.",
      },
      {
        id:      "mppt",
        name:    "Controladores MPPT",
        badge:   "MPPT",
        tagline: "20 – 100 A · 12/24/48 V · 98 % efic.",
        img:     `https://images.unsplash.com/photo-1559302504-64aae6ca6b6d${Q}`,
        imgL:    `https://images.unsplash.com/photo-1559302504-64aae6ca6b6d${QL}`,
        waMsg:   "Quiero cotizar controladores MPPT",
        specs: [
          ["Corriente de carga","20 / 40 / 60 / 100 A"],
          ["Voltaje de sistema","12 V / 24 V / 48 V (auto)"],
          ["Eficiencia MPPT",   "≥ 98 %"],
          ["Voltaje PV máx.",   "150 / 200 V"],
          ["Display",           "LCD + Bluetooth"],
          ["Protecciones",      "Sobrecarga · Inversión de pol."],
          ["Baterías compat.",  "LiFePO4 · Li-Ion · AGM · GEL"],
        ],
        desc: "Controladores de carga MPPT de alta eficiencia para maximizar la generación solar en cualquier condición de nubosidad o temperatura. Soportan baterías LiFePO4 con perfil de carga programable vía Bluetooth. Display LCD con historial de datos.",
      },
    ],
  },
  {
    id: "baterias",
    label: "Celdas de Litio",
    icon: "🔋",
    items: [
      {
        id:      "18650",
        name:    "Celda de Litio 18650",
        badge:   "Li-Ion NCM",
        tagline: "2,550 mAh · 3.6 V · EVE · 1,000 ciclos",
        img:     "/productos/celdas/18650/1.avif",
        imgL:    "/productos/celdas/18650/1.avif",
        images:  ["/productos/celdas/18650/1.avif", "/productos/celdas/18650/2.avif"],
        waMsg:   "Quiero cotizar celdas de litio 18650 EVE",
        specs: [
          ["Modelo",               "EVE 18650 26V"],
          ["Capacidad nominal",    "2,550 mAh"],
          ["Voltaje nominal",      "3.6 V"],
          ["Energía por celda",    "9.18 Wh"],
          ["Cátodo",               "NCM (Níquel Cobalto Manganeso)"],
          ["Tipo",                 "Li-Ion líquido recargable"],
          ["Ciclos de vida",       "≥ 1,000 ciclos"],
          ["Temp. operación",      "0 °C a 45 °C"],
          ["Dimensiones",          "Ø 18 mm × 65 mm"],
          ["Peso",                 "45 ± 2 g"],
          ["Aplicaciones",         "E-bikes · Scooters · Vehículos eléctricos · Solar · UPS · Montacargas"],
          ["Certificaciones",      "MSDS · CE · RoHS"],
        ],
        desc: "Celda cilíndrica 18650 de EVE Energy, marca Tier-1 de Guangdong, China. Con 2,550 mAh y química NCM ofrece alta densidad de energía para aplicaciones de movilidad eléctrica, herramientas de potencia y sistemas de almacenamiento solar. 1,000 ciclos de vida garantizados con prueba de capacidad verificable.",
      },
      {
        id:      "21700",
        name:    "Celdas de Litio 21700",
        badge:   "Li-Ion NCM",
        tagline: "5,000 mAh · 3.6 V · EVE · 18.25 Wh",
        img:     "/productos/celdas/21700/1.avif",
        imgL:    "/productos/celdas/21700/1.avif",
        images:  ["/productos/celdas/21700/1.avif", "/productos/celdas/21700/2.avif"],
        waMsg:   "Quiero cotizar celdas de litio 21700 EVE",
        specs: [
          ["Modelo",              "EVE 21700 50E"],
          ["Capacidad nominal",   "5,000 mAh"],
          ["Voltaje nominal",     "3.6 V"],
          ["Energía por celda",   "18.25 Wh"],
          ["Cátodo / Ánodo",      "NCM"],
          ["Tipo",                "Li-Ion líquido recargable"],
          ["Ciclos de vida",      "≥ 1,000 ciclos"],
          ["Temp. operación",     "0 °C a 45 °C"],
          ["Peso",                "69 g"],
          ["Aplicaciones",        "E-bikes · Scooters · Vehículos · Solar · UPS · Herramientas · Marina"],
          ["Certificaciones",     "CE · RoHS · UN38.3"],
        ],
        desc: "Celda cilíndrica 21700 de EVE Energy con 5,000mAh y química NCM. Mayor capacidad y densidad energética que la 18650, con 18.25Wh por celda. Ideal para packs de e-bikes de alto rendimiento, motos eléctricas, herramientas de potencia y sistemas de almacenamiento portátil. 1,000 ciclos de vida garantizados.",
      },
      {
        id:      "33140",
        name:    "Celdas LiFePO4 33140",
        badge:   "LiFePO4",
        tagline: "15,000 mAh · 3.2 V · 3,000 ciclos",
        img:     "/productos/celdas/33140/3.avif",
        imgL:    "/productos/celdas/33140/3.avif",
        images:  ["/productos/celdas/33140/3.avif", "/productos/celdas/33140/1.avif", "/productos/celdas/33140/2.avif", "/productos/celdas/33140/4.avif"],
        waMsg:   "Quiero cotizar celdas LiFePO4 33140",
        specs: [
          ["Modelo",              "33140 — 3.2V 15Ah"],
          ["Capacidad nominal",   "15,000 mAh (15 Ah)"],
          ["Voltaje nominal",     "3.2 V"],
          ["Cátodo",              "LiFePO4 (Fosfato de Hierro Litio)"],
          ["Tipo",                "Solid State"],
          ["Ciclos de vida",      "≥ 3,000 ciclos"],
          ["Temp. operación",     "-22 °C a 45 °C"],
          ["Dimensiones",         "33 × 140 mm"],
          ["Peso",                "270 g"],
          ["Garantía",            "1 año"],
          ["Aplicaciones",        "E-bikes · Scooters · Solar · UPS · Marina · Drones · Montacargas"],
        ],
        desc: "Celda cilíndrica LiFePO4 formato 33140 con 15Ah y química de fosfato de hierro litio. Ofrece 3,000 ciclos de vida, alta estabilidad térmica y cero riesgo de ignición espontánea. Ideal para packs de motos eléctricas, triciclos de carga, sistemas solares y aplicaciones que requieren alta corriente de descarga.",
      },
      {
        id:      "prismatica",
        name:    "Celdas LiFePO4 Prismáticas EVE",
        badge:   "LiFePO4 Prismatic",
        tagline: "102 – 314 Ah · 3.2 V · 4,000 – 8,000 ciclos · Grado A",
        img:     "/productos/celdas/prismatica/1.avif",
        imgL:    "/productos/celdas/prismatica/1.avif",
        images:  ["/productos/celdas/prismatica/1.avif", "/productos/celdas/prismatica/2.avif", "/productos/celdas/prismatica/3.avif", "/productos/celdas/prismatica/4.avif", "/productos/celdas/prismatica/5.avif", "/productos/celdas/prismatica/6.avif"],
        waMsg:   "Quiero cotizar celdas LiFePO4 prismáticas EVE",
        specs: [
          ["Modelos disponibles",     "102Ah · 105Ah · 150Ah · 230Ah · 280Ah · 304Ah · 314Ah"],
          ["Voltaje nominal",         "3.2 V por celda"],
          ["Cátodo",                  "LiFePO4 (Fosfato de Hierro Litio)"],
          ["Grado",                   "A — Full Certification CE / DE / EU"],
          ["Ciclos de vida",          "4,000 – 8,000+ ciclos (según modelo)"],
          ["Carga/descarga cont.",    "1C / 1C · Pulso: 2C / 2C"],
          ["Peso por celda",          "~1.98 kg (102Ah) – ~5.42 kg (314Ah)"],
          ["Temp. descarga",          "-30 °C a 60 °C (según modelo)"],
          ["Temp. carga",             "0 °C a 55 °C"],
          ["Temp. almacenamiento",    "0 °C a 35 °C"],
          ["Aplicaciones",            "Solar · UPS · Marina · Montacargas · Vehículos eléctricos"],
          ["Certificaciones",         "CE · IEC · UN38.3"],
        ],
        desc: "Gama completa de celdas LiFePO4 prismáticas EVE Energy Grado A, desde 102Ah hasta 314Ah. Los modelos de mayor capacidad (280Ah / 314Ah) alcanzan 8,000+ ciclos, ideales para sistemas de almacenamiento solar residencial e industrial. Las celdas 102Ah y 105Ah ofrecen 5,000 ciclos para packs de alta densidad. Todas con certificación CE/DE/EU y BMS compatible.",
      },
    ],
  },
];

export const SERVICES = [
  {
    id: "fabricacion",
    label: "Fabricación",
    icon: "⚙️",
    items: [
      {
        id:      "fab-pack",
        name:    "Fabricación de Pack de Batería",
        badge:   "A medida",
        tagline: "Li-Ion · LiFePO4 · Cualquier voltaje y capacidad · Informe técnico incluido",
        img:     "/servicios/fabricacion/fab-pack/1.avif",
        imgL:    "/servicios/fabricacion/fab-pack/1.avif",
        images:  ["/servicios/fabricacion/fab-pack/1.avif","/servicios/fabricacion/fab-pack/2.avif","/servicios/fabricacion/fab-pack/3.avif","/servicios/fabricacion/fab-pack/4.avif","/servicios/fabricacion/fab-pack/5.avif","/servicios/fabricacion/fab-pack/6.avif","/servicios/fabricacion/fab-pack/7.avif","/servicios/fabricacion/fab-pack/8.avif","/servicios/fabricacion/fab-pack/9.avif","/servicios/fabricacion/fab-pack/10.avif"],
        waMsg:   "Hola, quiero información sobre fabricación de pack de batería a medida",
        specs: [
          ["Químicas disponibles",   "Li-Ion NCM (18650/21700) · LiFePO4 (32700/prismática)"],
          ["Voltajes",               "12V · 24V · 36V · 48V · 60V · 72V · custom"],
          ["Capacidades",            "Desde 5Ah hasta proyectos de gran escala"],
          ["Ejemplo fabricado",      "60V 12.5Ah — 16S5P · 80 celdas EVE ICR18650 · 720 Wh"],
          ["Configuración de celdas","Series y paralelo a medida del proyecto"],
          ["Ensamblaje",             "Soldadura por puntos neumática · níquel 0.15 mm"],
          ["Soportes",               "Honeycomb holders (alineación y separación de celdas)"],
          ["Verificación de celdas", "Voltaje + impedancia interna + capacidad celda a celda"],
          ["BMS integrado",          "Protección: sobrecarga · sobredescarga · cortocircuito · balanceo"],
          ["Balance garantizado",    "ΔV entre grupos ≤ 0.02V (verificado con multímetro de pinza)"],
          ["Aislamiento",            "Triple: papel antiestático · cinta térmica · fibra de vidrio"],
          ["Pruebas finales",        "Carga completa + descarga controlada + verificación BMS"],
          ["Carcasa",                "ABS · Aluminio · IP54/IP65 según proyecto"],
          ["Conectores",             "Anderson · XT60 · XLR · custom según requerimiento"],
          ["Informe técnico",        "Firmado por Ingeniero Responsable (Nº de informe único)"],
          ["Certificado de garantía","Incluido · mín. 1 año según proyecto"],
          ["Aplicaciones",           "E-bike · Moto eléctrica · Scooter · Solar · UPS · Marina · Industria"],
        ],
        desc: "Diseñamos y fabricamos packs de baterías de litio completamente a medida. Nuestro proceso incluye selección y verificación celda a celda (voltaje, impedancia, capacidad), ensamblaje con soportes honeycomb, soldadura por puntos neumática con níquel de alta conductividad, instalación de BMS con protecciones completas y triple aislamiento. Cada pack pasa por pruebas de carga/descarga controlada y se entrega con informe técnico numerado y certificado de garantía firmado por ingeniero responsable.",
      },
      {
        id:      "fab-conversion",
        name:    "Conversión a Litio",
        badge:   "Conversión",
        tagline: "Reemplaza plomo-ácido por litio · Sin modificar cableado ni inversor",
        video:   "/servicios/fabricacion/fab-conversion/conversion.mp4",
        img:     `https://images.unsplash.com/photo-1620570026071-0f4e3a1de148${Q}`,
        imgL:    `https://images.unsplash.com/photo-1620570026071-0f4e3a1de148${QL}`,
        waMsg:   "Hola, quiero información sobre conversión de batería plomo a litio",
        comparison: {
          cols: [
            { name: "LiFePO4",    recommended: true  },
            { name: "Li-Ion NCM", recommended: false },
            { name: "Plomo-ácido",recommended: false },
          ],
          rows: [
            { icon: "🔄", label: "Ciclos de vida",     vals: ["≥ 6,000",   "≥ 1,000",    "300 – 500"],   win: [0],    best: 0 },
            { icon: "⚡", label: "Eficiencia",          vals: ["> 95%",     "> 95%",      "70 – 80%"],    win: [0, 1], best: 0 },
            { icon: "⚖️", label: "Peso relativo",       vals: ["−70%",      "−65%",       "Referencia"],  win: [0, 1], best: 0 },
            { icon: "🔧", label: "Mantenimiento",       vals: ["Ninguno",   "Ninguno",    "Periódico"],   win: [0, 1], best: 0 },
            { icon: "🌡️", label: "Seguridad térmica",   vals: ["Muy alta",  "Alta",       "Media"],       win: [0],    best: 0 },
            { icon: "📅", label: "Vida útil",           vals: ["10+ años",  "3–5 años",   "1–2 años"],    win: [0],    best: 0 },
          ],
        },
        specs: [
          ["Reemplazo directo",    "Sin modificar cableado ni inversor existente"],
          ["Químicas disponibles", "LiFePO4 (recomendada) · Li-Ion NCM"],
          ["Voltajes",             "12V · 24V · 36V · 48V · 60V · 72V"],
          ["BMS incluido",         "Configurado para el cargador actual del cliente"],
          ["Diagnóstico previo",   "Evaluación del sistema eléctrico existente sin costo"],
          ["Proceso",              "Desmontaje · reemplazo · configuración BMS · prueba de carga"],
          ["Certificado técnico",  "Firmado por Ingeniero Responsable"],
          ["Garantía",             "1 año sobre el pack instalado"],
          ["Aplicaciones",         "Motos · Scooters · Triciclos · UPS · Solar · Marina · Montacargas"],
        ],
        desc: "Convertimos tu batería de plomo-ácido AGM/GEL a litio LiFePO4 sin tocar el cableado ni cambiar el inversor. El proceso incluye diagnóstico eléctrico del sistema, desmontaje de la batería antigua, instalación del pack de litio con BMS configurado para tu cargador actual y prueba de carga completa. El resultado: hasta 10× más ciclos de vida, >95% de eficiencia energética, hasta 70% menos peso y cero mantenimiento. Cada conversión incluye certificado técnico firmado por ingeniero responsable.",
      },
    ],
  },
  {
    id: "reparacion",
    label: "Reparación",
    icon: "🔧",
    items: [
      {
        id:      "rep-bateria",
        name:    "Reparación de Batería de Litio",
        badge:   "Reparación",
        tagline: "Diagnóstico · Reemplazo de celdas · Recertificación",
        img:     `https://images.unsplash.com/photo-1574169208507-84376144848b${Q}`,
        imgL:    `https://images.unsplash.com/photo-1574169208507-84376144848b${QL}`,
        waMsg:   "Hola, quiero información sobre reparación de batería de litio",
        specs: [
          ["Diagnóstico",        "Prueba de capacidad y análisis celda por celda"],
          ["Tipos",              "Li-Ion · LiFePO4"],
          ["Servicio",           "Reemplazo de celdas · BMS · conectores"],
          ["Balanceo",           "Ecualización de celdas incluida"],
          ["Recertificación",    "Certificado técnico post-reparación"],
          ["Aplicaciones",       "E-bikes · Motos · Scooters · UPS · Solar"],
          ["Garantía",           "3 meses sobre el trabajo realizado"],
        ],
        desc: "Diagnóstico y reparación de packs de baterías de litio. Identificamos celdas defectuosas mediante prueba de capacidad individual, reemplazamos con celdas Grado A y recertificamos el pack. Extendemos la vida útil evitando el costo de una batería nueva.",
      },
      {
        id:      "rep-bms",
        name:    "Reparación de BMS",
        badge:   "BMS",
        tagline: "Diagnóstico · Reemplazo · Actualización de parámetros",
        img:     `https://images.unsplash.com/photo-1518770660439-4636190af475${Q}`,
        imgL:    `https://images.unsplash.com/photo-1518770660439-4636190af475${QL}`,
        waMsg:   "Hola, quiero información sobre reparación o reemplazo de BMS",
        specs: [
          ["Diagnóstico",        "Lectura de fallas y parámetros"],
          ["Servicio",           "Reparación o reemplazo de BMS"],
          ["Configuración",      "Ajuste de voltaje de corte · balanceo · protecciones"],
          ["Compatibilidad",     "Li-Ion · LiFePO4 · cualquier marca"],
          ["Comunicación",       "UART · CAN · RS485 según modelo"],
          ["Garantía",           "3 meses sobre el trabajo realizado"],
        ],
        desc: "El BMS (Battery Management System) es el cerebro del pack. Reparamos o reemplazamos BMS defectuosos y los configuramos con los parámetros correctos para tu batería. Solucionamos problemas de apagado inesperado, error de balanceo y sobreprotección.",
      },
    ],
  },
];
